aop:
  - changed-files:
      - any-glob-to-any-file:
          - src/main/java/de/tum/cit/ase/ares/api/aop/**/*
          - src/test/java/de/tum/cit/ase/ares/api/aop/**/*
          - src/test/java/de/tum/cit/ase/ares/integration/aop/**/*
          - documentation/docs/contributor/subsystems/aop/**/*
          - documentation/docs/contributor/technologies/aop-tests/**/*

architecture:
  - changed-files:
      - any-glob-to-any-file:
          - src/main/java/de/tum/cit/ase/ares/api/architecture/**/*
          - src/test/java/de/tum/cit/ase/ares/api/architecture/**/*
          - src/test/java/de/tum/cit/ase/ares/integration/architecture/**/*
          - documentation/docs/contributor/subsystems/architecture/**/*
          - documentation/docs/contributor/technologies/architecture-tests/**/*

ast:
  - changed-files:
      - any-glob-to-any-file:
          - src/main/java/de/tum/cit/ase/ares/api/ast/**/*
          - src/test/java/de/tum/cit/ase/ares/integration/AstAssertionTest.java
          - src/test/java/de/tum/cit/ase/ares/integration/testuser/subject/structural/astTestFiles/**/*

policy:
  - changed-files:
      - any-glob-to-any-file:
          - src/main/java/de/tum/cit/ase/ares/api/policy/**/*
          - src/test/java/de/tum/cit/ase/ares/api/policy/**/*
          - src/test/resources/de/tum/cit/ase/ares/integration/testuser/securitypolicies/**/*
          - documentation/docs/contributor/subsystems/policy/**/*
          - documentation/docs/contributor/policy/**/*

docs:
  - changed-files:
      - any-glob-to-any-file:
          - documentation/**/*
          - "*.md"
          - SECURITY.md

tests:
  - changed-files:
      - any-glob-to-any-file:
          - src/test/**/*

securitytest:
  - changed-files:
      - any-glob-to-any-file:
          - src/main/java/de/tum/cit/ase/ares/api/securitytest/**/*
          - src/test/java/de/tum/cit/ase/ares/api/securitytest/**/*
          - documentation/docs/contributor/subsystems/securitytest/**/*

other:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
          - .coderabbit.yaml
          - .whitesource
          - .gitignore
          - LICENSE
          - pom.xml
          - renovate.json
