package de.tum.cit.ase.ares.api.securitytest.java.writer;

import javax.annotation.Nonnull;

import de.tum.cit.ase.ares.api.policy.policySubComponents.TestBehaviorConfiguration;

/**
 * The Java source text of the failure-reporting hooks a precompile run writes
 * into an exercise. The hooks replace a failed test's real error with the
 * policy's message, so the setting works in an exercise without Ares at run
 * time. Generated as text, like the settings class, so no classpath resource
 * can stand in for them.
 *
 * @since 2.1.5
 * @author Luka Petrovic
 */
final class FailureReportingSources {

	/** The reserved package every generated class lives in. */
	static final String GENERATED_PACKAGE = "de.tum.cit.ase.ares.generated";

	/** Simple name of the generated JUnit Jupiter extension. */
	static final String JUPITER_HOOK = "GeneratedFailureReporting";

	/** Simple name of the generated jqwik lifecycle hook. */
	static final String JQWIK_HOOK = "GeneratedJqwikFailureReporting";

	/** Simple name of the generated JUnit sentinel test. */
	static final String JUPITER_SENTINEL = "GeneratedFailureReportingSentinelTest";

	/** Simple name of the generated jqwik sentinel test. */
	static final String JQWIK_SENTINEL = "GeneratedJqwikFailureReportingSentinelTest";

	/**
	 * Message key of the fixed text a timed-out test shows instead of its error.
	 */
	static final String TIMEOUT_KEY = "generated.failure.reporting.timeout";

	/** Message key of the text a sentinel shows when its hook is not active. */
	static final String INACTIVE_KEY = "generated.failure.reporting.inactive";

	/** Message key of the text shown when jqwik is present but not covered. */
	static final String JQWIK_MISSING_KEY = "generated.failure.reporting.jqwik.missing";

	/** Placeholder for the copied {@code Messages} class in the source texts. */
	private static final String MESSAGES = "@MESSAGES@";

	/** Placeholder for the settings class in the source texts. */
	private static final String SETTINGS = "@SETTINGS@";

	/** Placeholder for the switch field of the settings class. */
	private static final String ENABLED = "@ENABLED@";

	/** Placeholder for the message field of the settings class. */
	private static final String MESSAGE = "@MESSAGE@";

	/** Placeholder for whether the jqwik hook was generated beside the sentinel. */
	private static final String JQWIK_GENERATED = "@JQWIK_GENERATED@";

	/**
	 * Source text of the JUnit Jupiter hook, before the placeholders are filled.
	 */
	private static final String JUPITER_HOOK_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import java.util.concurrent.TimeoutException;

			import org.junit.jupiter.api.extension.ExtensionContext;
			import org.junit.jupiter.api.extension.LifecycleMethodExecutionExceptionHandler;
			import org.junit.jupiter.api.extension.TestExecutionExceptionHandler;
			import org.opentest4j.TestAbortedException;

			/**
			 * Generated by Ares. Shows the policy's message instead of a failed test's real
			 * error; a timeout shows a fixed text. Do not edit: regenerate instead.
			 */
			public final class GeneratedFailureReporting
					implements TestExecutionExceptionHandler, LifecycleMethodExecutionExceptionHandler {

				/** Set once JUnit has created this extension; the sentinel test checks it. */
				private static volatile boolean active;

				/** Creates the extension, which JUnit does before any test runs. */
				public GeneratedFailureReporting() {
					markActive();
				}

				/** Records that JUnit created this extension. */
				private static void markActive() {
					active = true;
				}

				/**
				 * Whether JUnit created this extension in this test run.
				 *
				 * @return true once the extension exists
				 */
				public static boolean isActive() {
					return active;
				}

				/**
				 * Replaces a failure of a test method. The generated sentinel's own failure is
				 * kept, since it only ever says that this reporting is incomplete.
				 *
				 * @param context   the test's context
				 * @param throwable the real failure
				 * @throws Throwable the failure to report instead
				 */
				@Override
				public void handleTestExecutionException(ExtensionContext context, Throwable throwable) throws Throwable {
					throw isSentinel(context) ? throwable : replacementFor(throwable);
				}

				/**
				 * Whether the failing test is the generated sentinel, which no student class
				 * can pose as because the build rejects student code in this package.
				 *
				 * @param context the test's context
				 * @return true for the generated sentinel test
				 */
				static boolean isSentinel(ExtensionContext context) {
					return context.getTestClass().map(Class::getName)
							.filter("de.tum.cit.ase.ares.generated.GeneratedFailureReportingSentinelTest"::equals).isPresent();
				}

				/**
				 * Replaces a failure of a {@code @BeforeAll} method.
				 *
				 * @param context   the test's context
				 * @param throwable the real failure
				 * @throws Throwable the failure to report instead
				 */
				@Override
				public void handleBeforeAllMethodExecutionException(ExtensionContext context, Throwable throwable)
						throws Throwable {
					throw replacementFor(throwable);
				}

				/**
				 * Replaces a failure of a {@code @BeforeEach} method.
				 *
				 * @param context   the test's context
				 * @param throwable the real failure
				 * @throws Throwable the failure to report instead
				 */
				@Override
				public void handleBeforeEachMethodExecutionException(ExtensionContext context, Throwable throwable)
						throws Throwable {
					throw replacementFor(throwable);
				}

				/**
				 * Replaces a failure of an {@code @AfterEach} method.
				 *
				 * @param context   the test's context
				 * @param throwable the real failure
				 * @throws Throwable the failure to report instead
				 */
				@Override
				public void handleAfterEachMethodExecutionException(ExtensionContext context, Throwable throwable)
						throws Throwable {
					throw replacementFor(throwable);
				}

				/**
				 * Replaces a failure of an {@code @AfterAll} method.
				 *
				 * @param context   the test's context
				 * @param throwable the real failure
				 * @throws Throwable the failure to report instead
				 */
				@Override
				public void handleAfterAllMethodExecutionException(ExtensionContext context, Throwable throwable)
						throws Throwable {
					throw replacementFor(throwable);
				}

				/**
				 * The failure to report instead of the real one. A skipped test stays skipped
				 * without its reason, a timeout shows the fixed text, everything else the
				 * policy's message.
				 *
				 * @param throwable the real failure
				 * @return the failure to report
				 */
				static Throwable replacementFor(Throwable throwable) {
					if (!@SETTINGS@.@ENABLED@) {
						return throwable;
					}
					if (throwable instanceof TestAbortedException) {
						return new TestAbortedException();
					}
					if (throwable instanceof TimeoutException) {
						return new AssertionError(@MESSAGES@.localized("generated.failure.reporting.timeout"));
					}
					return new AssertionError(@SETTINGS@.@MESSAGE@);
				}
			}
			""";

	/** Source text of the jqwik hook, before the placeholders are filled. */
	private static final String JQWIK_HOOK_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import net.jqwik.api.lifecycle.AroundPropertyHook;
			import net.jqwik.api.lifecycle.PropagationMode;
			import net.jqwik.api.lifecycle.PropertyExecutionResult;
			import net.jqwik.api.lifecycle.PropertyExecutor;
			import net.jqwik.api.lifecycle.PropertyLifecycleContext;

			/**
			 * Generated by Ares. Shows the policy's message instead of a failed property's
			 * real error. Do not edit: regenerate instead.
			 */
			public final class GeneratedJqwikFailureReporting implements AroundPropertyHook {

				/** Set once this hook has wrapped a property; the sentinel test checks it. */
				private static volatile boolean active;

				/** Records that this hook wrapped a property. */
				private static void markActive() {
					active = true;
				}

				/**
				 * Whether this hook has wrapped a property in this test run, which includes
				 * the sentinel itself.
				 *
				 * @return true once the hook has wrapped a property
				 */
				public static boolean isActive() {
					return active;
				}

				/**
				 * Applies this hook to every property, not only to the container jqwik
				 * registers it on.
				 *
				 * @return every descendant
				 */
				@Override
				public PropagationMode propagateTo() {
					return PropagationMode.ALL_DESCENDANTS;
				}

				/**
				 * Runs the property and replaces the error of a failed or aborted run with the
				 * policy's message.
				 *
				 * @param context  the property's context
				 * @param property runs the property
				 * @return the result to report
				 * @throws Throwable whatever running the property throws
				 */
				@Override
				public PropertyExecutionResult aroundProperty(PropertyLifecycleContext context, PropertyExecutor property)
						throws Throwable {
					markActive();
					PropertyExecutionResult result = property.execute();
					if (!@SETTINGS@.@ENABLED@ || result.status() == PropertyExecutionResult.Status.SUCCESSFUL) {
						return result;
					}
					return result.mapTo(result.status(), new AssertionError(@SETTINGS@.@MESSAGE@));
				}

				/**
				 * Places this hook outside every other around-property hook, so it sees the
				 * final result.
				 *
				 * @return the lowest proximity
				 */
				@Override
				public int aroundPropertyProximity() {
					return Integer.MIN_VALUE;
				}
			}
			""";

	/**
	 * Source text of the JUnit sentinel test, before the placeholders are filled.
	 */
	private static final String JUPITER_SENTINEL_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import org.junit.jupiter.api.Test;

			/**
			 * Generated by Ares. Fails when the generated failure reporting is not active,
			 * or when jqwik is present without its hook, so a missing hook shows up as a
			 * red test instead of real errors.
			 */
			class GeneratedFailureReportingSentinelTest {

				/** Whether the generator wrote the jqwik hook beside this test. */
				private static final boolean JQWIK_HOOK_GENERATED = @JQWIK_GENERATED@;

				/** Checks that JUnit created the generated failure-reporting extension. */
				@Test
				void failureReportingIsActive() {
					if (!GeneratedFailureReporting.isActive()) {
						throw new AssertionError(@MESSAGES@.localized("generated.failure.reporting.inactive"));
					}
				}

				/** Checks that jqwik, when the test run has it, got its hook as well. */
				@Test
				void jqwikIsCoveredWhenPresent() {
					if (!JQWIK_HOOK_GENERATED && jqwikIsPresent()) {
						throw new AssertionError(@MESSAGES@.localized("generated.failure.reporting.jqwik.missing"));
					}
				}

				/**
				 * Whether jqwik's hook interface is on this test run's class path.
				 *
				 * @return true when jqwik can run properties here
				 */
				private static boolean jqwikIsPresent() {
					try {
						Class.forName("net.jqwik.api.lifecycle.AroundPropertyHook", false,
								GeneratedFailureReportingSentinelTest.class.getClassLoader());
						return true;
					} catch (ClassNotFoundException absent) {
						return false;
					}
				}
			}
			""";

	/**
	 * Source text of the jqwik sentinel test, before the placeholders are filled.
	 */
	private static final String JQWIK_SENTINEL_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import net.jqwik.api.Example;

			/**
			 * Generated by Ares. Fails when the generated jqwik failure reporting did not
			 * wrap this property, so a missing hook shows up as a red test instead of
			 * real errors.
			 */
			class GeneratedJqwikFailureReportingSentinelTest {

				/** Checks that the generated failure-reporting hook wrapped this property. */
				@Example
				void failureReportingIsActive() {
					if (!GeneratedJqwikFailureReporting.isActive()) {
						throw new AssertionError(@MESSAGES@.localized("generated.failure.reporting.inactive"));
					}
				}
			}
			""";

	/** Prevents instantiation: this class only holds source texts. */
	private FailureReportingSources() {
		throw new IllegalStateException("FailureReportingSources is a utility class and should not be instantiated");
	}

	/**
	 * The JUnit Jupiter hook's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterHook(@Nonnull String messagesClass) {
		return fill(JUPITER_HOOK_SOURCE, messagesClass);
	}

	/**
	 * The jqwik hook's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jqwikHook(@Nonnull String messagesClass) {
		return fill(JQWIK_HOOK_SOURCE, messagesClass);
	}

	/**
	 * The JUnit sentinel test's source.
	 *
	 * @param messagesClass      fully qualified name of the copied
	 *                           {@code Messages}.
	 * @param jqwikHookGenerated whether the jqwik hook is generated beside it.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterSentinel(@Nonnull String messagesClass, boolean jqwikHookGenerated) {
		return fill(JUPITER_SENTINEL_SOURCE, messagesClass).replace(JQWIK_GENERATED,
				String.valueOf(jqwikHookGenerated));
	}

	/**
	 * The jqwik sentinel test's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jqwikSentinel(@Nonnull String messagesClass) {
		return fill(JQWIK_SENTINEL_SOURCE, messagesClass);
	}

	/**
	 * Fills the placeholders of a source text.
	 *
	 * @param source        the source text with placeholders.
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text with every placeholder replaced
	 */
	@Nonnull
	private static String fill(@Nonnull String source, @Nonnull String messagesClass) {
		return source.replace(MESSAGES, messagesClass).replace(SETTINGS, TestBehaviorConfiguration.GENERATED_CLASS_NAME)
				.replace(ENABLED, TestBehaviorConfiguration.PRIVILEGED_EXCEPTIONS_ENABLED_FIELD_NAME)
				.replace(MESSAGE, TestBehaviorConfiguration.PRIVILEGED_EXCEPTIONS_MESSAGE_FIELD_NAME)
				.replace("\n", System.lineSeparator());
	}
}
