package de.tum.cit.ase.ares.api.securitytest.java.writer;

import javax.annotation.Nonnull;

import de.tum.cit.ase.ares.api.policy.policySubComponents.TestBehaviorConfiguration;

/**
 * The Java source text of the failure-reporting hooks a precompile run writes
 * into an exercise. The hooks replace a failed test's real error with the
 * policy's message, so the setting works in an exercise without Ares at run
 * time. Generated as text, like the settings class, so no classpath resource
 * can stand in for them.
 *
 * @since 2.1.5
 * @author Luka Petrovic
 */
final class FailureReportingSources {

	/** Simple name of the generated JUnit Jupiter extension. */
	static final String JUPITER_HOOK = "GeneratedFailureReporting";

	/** Simple name of the generated JUnit sentinel test. */
	static final String JUPITER_SENTINEL = "GeneratedFailureReportingSentinelTest";

	/**
	 * Message key of the fixed text a timed-out test shows instead of its error.
	 */
	static final String TIMEOUT_KEY = "generated.failure.reporting.timeout";

	/** Message key of the text a sentinel shows when its hook is not active. */
	static final String INACTIVE_KEY = "generated.failure.reporting.inactive";

	/** Placeholder for the copied {@code Messages} class in the source texts. */
	private static final String MESSAGES = "@MESSAGES@";

	/** Placeholder for the settings class in the source texts. */
	private static final String SETTINGS = "@SETTINGS@";

	/** Placeholder for the switch field of the settings class. */
	private static final String ENABLED = "@ENABLED@";

	/** Placeholder for the message field of the settings class. */
	private static final String MESSAGE = "@MESSAGE@";

	/**
	 * Source text of the JUnit Jupiter hook, before the placeholders are filled.
	 */
	private static final String JUPITER_HOOK_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import java.lang.reflect.Constructor;
			import java.lang.reflect.Method;
			import java.util.Arrays;
			import java.util.Iterator;
			import java.util.List;
			import java.util.Spliterator;
			import java.util.Spliterators;
			import java.util.concurrent.TimeoutException;
			import java.util.stream.Stream;
			import java.util.stream.StreamSupport;

			import org.junit.jupiter.api.DynamicContainer;
			import org.junit.jupiter.api.DynamicNode;
			import org.junit.jupiter.api.extension.DynamicTestInvocationContext;
			import org.junit.jupiter.api.extension.ExtensionContext;
			import org.junit.jupiter.api.extension.InvocationInterceptor;
			import org.junit.jupiter.api.extension.LifecycleMethodExecutionExceptionHandler;
			import org.junit.jupiter.api.extension.ReflectiveInvocationContext;
			import org.junit.jupiter.api.extension.TestExecutionExceptionHandler;
			import org.opentest4j.TestAbortedException;

			/**
			 * Generated by Ares. Shows the policy's message instead of a failed test's real
			 * error; a timeout shows a fixed text. Do not edit: regenerate instead.
			 */
			public final class GeneratedFailureReporting
					implements TestExecutionExceptionHandler, LifecycleMethodExecutionExceptionHandler, InvocationInterceptor {

				/** The test guarded now, inherited by a worker another hook starts. */
				private static final InheritableThreadLocal<String> GUARDING = new InheritableThreadLocal<>();

				/**
				 * Whether this hook is guarding the named test in this invocation.
				 *
				 * @param test the test, as {@code fully.qualified.Class#method}
				 * @return true while that test runs inside this hook
				 */
				public static boolean isGuarding(String test) {
					return test.equals(GUARDING.get());
				}

				/**
				 * Marks this method as guarded only while the invocation runs.
				 *
				 * @param invocation runs the test
				 * @param invocationContext the method and its arguments
				 * @param context the test's context
				 * @throws Throwable the test's failure, handled by the exception handler
				 */
				@Override
				public void interceptTestMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext context) throws Throwable {
					GUARDING.set(context.getRequiredTestClass().getName() + "#" + context.getRequiredTestMethod().getName());
					try {
						invocation.proceed();
					} finally {
						GUARDING.remove();
					}
				}

				/**
				 * Replaces a failure of a test method. The generated sentinel's own failure is
				 * kept, since it only ever says that this reporting is incomplete.
				 *
				 * @param context   the test's context
				 * @param throwable the real failure
				 * @throws Throwable the failure to report instead
				 */
				@Override
				public void handleTestExecutionException(ExtensionContext context, Throwable throwable) throws Throwable {
					throw isSentinel(context) ? throwable : replacementFor(throwable);
				}

				/**
				 * Replaces a failure of a dynamic test, which no exception handler sees.
				 *
				 * @param invocation        runs the dynamic test
				 * @param invocationContext the dynamic test's invocation
				 * @param extensionContext  the dynamic test's context
				 * @throws Throwable the failure to report instead
				 */
				@Override
				public void interceptDynamicTest(Invocation<Void> invocation, DynamicTestInvocationContext invocationContext,
						ExtensionContext extensionContext) throws Throwable {
					try {
						invocation.proceed();
					} catch (Throwable throwable) {
						throw replacementFor(throwable);
					}
				}

				/**
				 * Replaces a failure of a test factory, including one that happens only while
				 * JUnit walks the tests it returned, which no exception handler sees.
				 *
				 * @param <T>               the factory's return type
				 * @param invocation        runs the factory
				 * @param invocationContext the factory call
				 * @param extensionContext  the factory's context
				 * @return the factory's tests, wrapped so walking them reports no real error
				 * @throws Throwable the failure to report instead
				 */
				@Override
				@SuppressWarnings("unchecked")
				public <T> T interceptTestFactoryMethod(Invocation<T> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					try {
						T result = invocation.proceed();
						Iterator<?> nodes = nodeIterator(result);
						return nodes == null ? result : (T) redactedNodes(nodes, result);
					} catch (Throwable throwable) {
						throw replacementFor(throwable);
					}
				}

				/**
				 * The tests a factory result holds, in every shape JUnit accepts.
				 *
				 * @param result the factory's result
				 * @return its elements, or null for a shape JUnit rejects itself
				 */
				static Iterator<?> nodeIterator(Object result) {
					if (result instanceof DynamicNode node) {
						return List.of(node).iterator();
					}
					if (result instanceof Stream<?> stream) {
						return stream.iterator();
					}
					if (result instanceof Iterable<?> iterable) {
						return iterable.iterator();
					}
					if (result instanceof Iterator<?> iterator) {
						return iterator;
					}
					if (result instanceof Object[] array) {
						return Arrays.asList(array).iterator();
					}
					return null;
				}

				/**
				 * A stream of the given tests that reports no real error while it is walked
				 * or closed, and closes the original stream when JUnit closes it.
				 *
				 * @param nodes  the tests
				 * @param source the original result, closed if it is a stream
				 * @return the redacting stream
				 */
				static Stream<DynamicNode> redactedNodes(Iterator<?> nodes, Object source) {
					Stream<DynamicNode> redacted = StreamSupport
							.stream(Spliterators.spliteratorUnknownSize(new RedactingIterator(nodes), Spliterator.ORDERED), false);
					return source instanceof Stream<?> stream ? redacted.onClose(() -> closeRedacted(stream)) : redacted;
				}

				/**
				 * Closes a factory's own stream, replacing any failure a close handler raises,
				 * since JUnit closes it only after this extension's interceptor returned.
				 *
				 * @param stream the factory's or a container's own stream
				 */
				static void closeRedacted(Stream<?> stream) {
					try {
						stream.close();
					} catch (Throwable throwable) {
						throw GeneratedFailureReporting.<RuntimeException>rethrow(replacementFor(throwable));
					}
				}

				/**
				 * The given test, with a container's children wrapped too, since JUnit walks
				 * them lazily as well.
				 *
				 * @param node the test or container
				 * @return the test, or a container whose children report no real error
				 */
				static DynamicNode redactedNode(Object node) {
					if (node instanceof DynamicContainer container) {
						Stream<? extends DynamicNode> children = container.getChildren();
						return DynamicContainer.dynamicContainer(container.getDisplayName(),
								container.getTestSourceUri().orElse(null), redactedNodes(children.iterator(), children));
					}
					return (DynamicNode) node;
				}

				/**
				 * Throws any throwable without declaring it, so an iterator can report the
				 * replaced failure.
				 *
				 * @param <E>       the type the compiler is told is thrown
				 * @param throwable the failure to throw
				 * @return never returns
				 * @throws E always
				 */
				@SuppressWarnings("unchecked")
				static <E extends Throwable> RuntimeException rethrow(Throwable throwable) throws E {
					throw (E) throwable;
				}

				/** Walks a factory's tests and replaces any failure while doing so. */
				static final class RedactingIterator implements Iterator<DynamicNode> {

					/** The factory's own tests. */
					private final Iterator<?> source;

					/**
					 * Wraps a factory's tests.
					 *
					 * @param source the factory's own tests
					 */
					RedactingIterator(Iterator<?> source) {
						this.source = source;
					}

					/**
					 * Whether another test follows, with any failure replaced.
					 *
					 * @return true if another test follows
					 */
					@Override
					public boolean hasNext() {
						try {
							return source.hasNext();
						} catch (Throwable throwable) {
							throw GeneratedFailureReporting.<RuntimeException>rethrow(replacementFor(throwable));
						}
					}

					/**
					 * The next test, with any failure replaced.
					 *
					 * @return the next test
					 */
					@Override
					public DynamicNode next() {
						Object next;
						try {
							next = source.next();
						} catch (Throwable throwable) {
							throw GeneratedFailureReporting.<RuntimeException>rethrow(replacementFor(throwable));
						}
						return redactedNode(next);
					}
				}

				/**
				 * Replaces a failure while the test class is created, such as from a field
				 * initialiser, which no exception handler sees.
				 *
				 * @param <T>               the test class
				 * @param invocation        creates the test instance
				 * @param invocationContext the constructor call
				 * @param extensionContext  the test class's context
				 * @return the test instance
				 * @throws Throwable the failure to report instead
				 */
				@Override
				public <T> T interceptTestClassConstructor(Invocation<T> invocation,
						ReflectiveInvocationContext<Constructor<T>> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					try {
						return invocation.proceed();
					} catch (Throwable throwable) {
						throw replacementFor(throwable);
					}
				}

				/**
				 * Whether the failing test is the generated sentinel, which no student class
				 * can pose as because the build rejects student code in this package.
				 *
				 * @param context the test's context
				 * @return true for the generated sentinel test
				 */
				static boolean isSentinel(ExtensionContext context) {
					return context.getTestClass().map(Class::getName)
							.filter("de.tum.cit.ase.ares.generated.GeneratedFailureReportingSentinelTest"::equals).isPresent();
				}

				/**
				 * Replaces a failure of a {@code @BeforeAll} method.
				 *
				 * @param context   the test's context
				 * @param throwable the real failure
				 * @throws Throwable the failure to report instead
				 */
				@Override
				public void handleBeforeAllMethodExecutionException(ExtensionContext context, Throwable throwable)
						throws Throwable {
					throw replacementFor(throwable);
				}

				/**
				 * Replaces a failure of a {@code @BeforeEach} method.
				 *
				 * @param context   the test's context
				 * @param throwable the real failure
				 * @throws Throwable the failure to report instead
				 */
				@Override
				public void handleBeforeEachMethodExecutionException(ExtensionContext context, Throwable throwable)
						throws Throwable {
					throw replacementFor(throwable);
				}

				/**
				 * Replaces a failure of an {@code @AfterEach} method.
				 *
				 * @param context   the test's context
				 * @param throwable the real failure
				 * @throws Throwable the failure to report instead
				 */
				@Override
				public void handleAfterEachMethodExecutionException(ExtensionContext context, Throwable throwable)
						throws Throwable {
					throw replacementFor(throwable);
				}

				/**
				 * Replaces a failure of an {@code @AfterAll} method.
				 *
				 * @param context   the test's context
				 * @param throwable the real failure
				 * @throws Throwable the failure to report instead
				 */
				@Override
				public void handleAfterAllMethodExecutionException(ExtensionContext context, Throwable throwable)
						throws Throwable {
					throw replacementFor(throwable);
				}

				/**
				 * The failure to report instead of the real one. A skipped test stays skipped
				 * without its reason, a timeout shows the fixed text, everything else the
				 * policy's message.
				 *
				 * @param throwable the real failure
				 * @return the failure to report
				 */
				static Throwable replacementFor(Throwable throwable) {
					if (isHiddenResult(throwable)) {
						return throwable;
					}
					if (!@SETTINGS@.@ENABLED@) {
						return throwable;
					}
					if (throwable instanceof TestAbortedException) {
						return new TestAbortedException();
					}
					if (throwable instanceof TimeoutException) {
						return new AssertionError(@MESSAGES@.localized("generated.failure.reporting.timeout"));
					}
					return new AssertionError(@SETTINGS@.@MESSAGE@);
				}

				/** Keeps a generated hidden result or scheduling notice unchanged. */
				private static boolean isHiddenResult(Throwable throwable) {
					String type = throwable.getClass().getName();
					return type.equals("de.tum.cit.ase.ares.generated.GeneratedHiddenTests$HiddenTestFailure")
							|| type.equals("de.tum.cit.ase.ares.generated.GeneratedHiddenTests$HiddenTestAbort")
							|| type.equals("de.tum.cit.ase.ares.generated.GeneratedHiddenTests$HiddenTestScheduled")
							|| type.equals("de.tum.cit.ase.ares.generated.GeneratedStrictTimeout$HiddenTestFailure");
				}
			}
			""";

	/**
	 * Source text of the JUnit sentinel test, before the placeholders are filled.
	 */
	private static final String JUPITER_SENTINEL_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import org.junit.jupiter.api.Test;

			/**
			 * Generated by Ares. Fails when the generated failure reporting is not active,
			 * so a missing hook shows up as a red test instead of real errors.
			 */
			class GeneratedFailureReportingSentinelTest {

				/** Checks that the generated reporting hook guards this invocation. */
				@Test
				void failureReportingIsActive() {
					if (!GeneratedFailureReporting.isGuarding(GeneratedFailureReportingSentinelTest.class.getName() + "#failureReportingIsActive")) {
						throw new AssertionError(@MESSAGES@.localized("generated.failure.reporting.inactive"));
					}
				}

			}
			""";

	/** Prevents instantiation: this class only holds source texts. */
	private FailureReportingSources() {
		throw new IllegalStateException("FailureReportingSources is a utility class and should not be instantiated");
	}

	/**
	 * The JUnit Jupiter hook's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterHook(@Nonnull String messagesClass) {
		return fill(JUPITER_HOOK_SOURCE, messagesClass);
	}

	/**
	 * The JUnit sentinel test's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterSentinel(@Nonnull String messagesClass) {
		return fill(JUPITER_SENTINEL_SOURCE, messagesClass);
	}

	/**
	 * Fills the placeholders of a source text.
	 *
	 * @param source        the source text with placeholders.
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text with every placeholder replaced
	 */
	@Nonnull
	private static String fill(@Nonnull String source, @Nonnull String messagesClass) {
		return source.replace(MESSAGES, messagesClass).replace(SETTINGS, TestBehaviorConfiguration.GENERATED_CLASS_NAME)
				.replace(ENABLED, TestBehaviorConfiguration.PRIVILEGED_EXCEPTIONS_ENABLED_FIELD_NAME)
				.replace(MESSAGE, TestBehaviorConfiguration.PRIVILEGED_EXCEPTIONS_MESSAGE_FIELD_NAME)
				.replace("\n", System.lineSeparator());
	}
}
