package de.tum.cit.ase.ares.api.securitytest.java.writer;

import javax.annotation.Nonnull;

import de.tum.cit.ase.ares.api.policy.policySubComponents.TestBehaviorConfiguration;

/**
 * The Java source text of the hidden-test hook a precompile run writes into an
 * exercise. It holds back the tests the policy makes hidden until the deadline
 * and hides why they failed, as Ares does for {@code @HiddenTest} in
 * postcompile, so the schedule works without Ares at run time.
 *
 * @since 2.1.5
 * @author Luka Petrovic
 */
final class HiddenTestsSources {

	/** Simple name of the generated JUnit extension. */
	static final String JUPITER_HOOK = "GeneratedHiddenTests";

	/** Simple name of the generated sentinel test. */
	static final String JUPITER_SENTINEL = "GeneratedHiddenTestsSentinelTest";

	/** Placeholder for the copied {@code Messages} class in the source texts. */
	private static final String MESSAGES = "@MESSAGES@";

	/** Placeholder for the settings class in the source texts. */
	private static final String SETTINGS = "@SETTINGS@";

	/** Placeholder for the deadline field of the settings class. */
	private static final String DEADLINE = "@DEADLINE@";

	/** Placeholder for the always-run-before field of the settings class. */
	private static final String ALWAYS_RUN_BEFORE = "@ALWAYS_RUN_BEFORE@";

	/** Placeholder for the hidden-test list field of the settings class. */
	private static final String HIDDEN = "@HIDDEN@";

	/** Placeholder for the public-test list field of the settings class. */
	private static final String PUBLIC = "@PUBLIC@";

	/**
	 * Placeholder for the unlisted-tests-are-hidden field of the settings class.
	 */
	private static final String UNLISTED = "@UNLISTED@";

	/**
	 * Placeholder for the exercise package the generated security tests live in.
	 */
	private static final String EXERCISE_PACKAGE = "@EXERCISE_PACKAGE@";

	/** Source text of the JUnit extension, before the placeholders are filled. */
	private static final String JUPITER_HOOK_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import java.lang.reflect.Method;
			import java.util.List;
			import java.util.Optional;
			import java.util.Set;
			import java.util.function.Function;

			import org.junit.jupiter.api.extension.DynamicTestInvocationContext;
			import org.junit.jupiter.api.extension.ExtensionContext;
			import org.junit.jupiter.api.extension.InvocationInterceptor;
			import org.junit.jupiter.api.extension.ReflectiveInvocationContext;
			import org.opentest4j.AssertionFailedError;

			/**
			 * Generated by Ares. Holds back the tests the policy makes hidden until the
			 * deadline and hides why they failed, as {@code @HiddenTest} does. Do not
			 * edit: regenerate instead.
			 */
			public final class GeneratedHiddenTests implements InvocationInterceptor {

				/** The hidden tests, as {@code pkg.Class} or {@code pkg.Class#method}. */
				private static final List<String> HIDDEN = List.of(@SETTINGS@.@HIDDEN@.split("\\n"));

				/** The public tests, as {@code pkg.Class} or {@code pkg.Class#method}. */
				private static final List<String> PUBLIC = List.of(@SETTINGS@.@PUBLIC@.split("\\n"));

				/** The security tests Ares generated into the exercise; they always run and report. */
				private static final Set<String> GENERATED_SECURITY_TESTS = Set.of(
						"@EXERCISE_PACKAGE@.ares.api.architecture.java.archunit.JavaArchunitTestCase",
						"@EXERCISE_PACKAGE@.ares.api.architecture.java.wala.JavaWalaTestCase");

				/**
				 * The test this hook is guarding right now, as {@code class#method}. Set only
				 * while the invocation runs, so it is evidence from the current run and never
				 * from an earlier one; inherited by a thread another hook starts for the test.
				 */
				private static final InheritableThreadLocal<String> GUARDING = new InheritableThreadLocal<>();

				/**
				 * Whether this hook is guarding the given test at this moment.
				 *
				 * @param test the test, as {@code fully.qualified.Class#method}
				 * @return true while its invocation runs inside this hook
				 */
				public static boolean isGuarding(String test) {
					return test.equals(GUARDING.get());
				}

				/**
				 * Guards a test method.
				 *
				 * @param invocation the method's invocation
				 * @param invocationContext the method and its arguments
				 * @param context the test's context
				 * @throws Throwable a hidden test's redacted failure, or the test's own
				 */
				@Override
				public void interceptTestMethod(Invocation<Void> invocation, ReflectiveInvocationContext<Method> invocationContext,
						ExtensionContext context) throws Throwable {
					guard(invocation, context);
				}

				/**
				 * Guards one invocation of a test template, such as a parameterised test.
				 *
				 * @param invocation the method's invocation
				 * @param invocationContext the method and its arguments
				 * @param context the test's context
				 * @throws Throwable a hidden test's redacted failure, or the test's own
				 */
				@Override
				public void interceptTestTemplateMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext context) throws Throwable {
					guard(invocation, context);
				}

				/**
				 * Guards a test factory.
				 *
				 * @param <T> the factory's result type
				 * @param invocation the factory's invocation
				 * @param invocationContext the factory and its arguments
				 * @param context the test's context
				 * @return the factory's result
				 * @throws Throwable a hidden test's redacted failure, or the test's own
				 */
				@Override
				public <T> T interceptTestFactoryMethod(Invocation<T> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext context) throws Throwable {
					return guard(invocation, context);
				}

				/**
				 * Guards a dynamic test, which counts as part of its factory.
				 *
				 * @param invocation the dynamic test's invocation
				 * @param invocationContext the dynamic test's context
				 * @param context the test's context
				 * @throws Throwable a hidden test's redacted failure, or the test's own
				 */
				@Override
				public void interceptDynamicTest(Invocation<Void> invocation, DynamicTestInvocationContext invocationContext,
						ExtensionContext context) throws Throwable {
					guard(invocation, context);
				}

				/**
				 * Marks the test as guarded for the length of its invocation, then runs it
				 * unchanged unless the policy hides it; a hidden test runs only after the
				 * deadline or before the always-run-before date, and any failure it raises is
				 * replaced by a fixed text.
				 *
				 * @param <T> the invocation's result type
				 * @param invocation the invocation
				 * @param context the test's context
				 * @return the invocation's result
				 * @throws Throwable a hidden test's redacted failure, or the test's own
				 */
				private static <T> T guard(Invocation<T> invocation, ExtensionContext context) throws Throwable {
					Optional<String> methodName = nearest(context, ExtensionContext::getTestMethod).map(Method::getName);
					Optional<Class<?>> testClass = nearest(context, ExtensionContext::getTestClass);
					GUARDING.set(testClass.map(Class::getName).orElse("") + "#" + methodName.orElse(""));
					try {
						return decide(invocation, testClass, methodName);
					} finally {
						GUARDING.remove();
					}
				}

				/**
				 * Runs a test unchanged unless the policy hides it, then holds it back before
				 * the deadline and replaces its failure after it.
				 *
				 * @param <T> the invocation's result type
				 * @param invocation the invocation
				 * @param testClass the test's class, if any
				 * @param methodName the test's method name, if any
				 * @return the invocation's result
				 * @throws Throwable a hidden test's redacted failure, or the test's own
				 */
				private static <T> T decide(Invocation<T> invocation, Optional<Class<?>> testClass,
						Optional<String> methodName) throws Throwable {
					if (testClass.isEmpty() || !isHidden(testClass.get(), methodName)) {
						return invocation.proceed();
					}
					long now = System.currentTimeMillis();
					if (now <= @SETTINGS@.@DEADLINE@ && now >= @SETTINGS@.@ALWAYS_RUN_BEFORE@) {
						invocation.skip();
						throw new AssertionFailedError(@MESSAGES@.localized("test_guard.hidden_test_before_deadline_message"));
					}
					try {
						return invocation.proceed();
					} catch (Throwable failure) {
						throw new AssertionError(@MESSAGES@.localized("test_guard.hidden_test_failed"));
					}
				}

				/**
				 * The nearest value up the context chain, so a dynamic test finds the
				 * method and class of the factory it belongs to.
				 *
				 * @param <T> the value's type
				 * @param context the test's context
				 * @param getter what to read from each context
				 * @return the value, if any context up the chain has one
				 */
				private static <T> Optional<T> nearest(ExtensionContext context,
						Function<ExtensionContext, Optional<T>> getter) {
					for (Optional<ExtensionContext> current = Optional.of(context); current.isPresent(); current = current.get()
							.getParent()) {
						Optional<T> value = getter.apply(current.get());
						if (value.isPresent()) {
							return value;
						}
					}
					return Optional.empty();
				}

				/**
				 * Whether the policy makes the test hidden. Generated classes never are.
				 * Otherwise the nearest entry wins: the test's own class with its method,
				 * then that class, then each enclosing class; without one, the policy's
				 * setting for unlisted tests decides.
				 *
				 * @param testClass the test's class
				 * @param methodName the test's method, if any
				 * @return true when the test is hidden
				 */
				private static boolean isHidden(Class<?> testClass, Optional<String> methodName) {
					if (testClass.getName().startsWith("de.tum.cit.ase.ares.generated.")
							|| GENERATED_SECURITY_TESTS.contains(testClass.getName())) {
						return false;
					}
					Optional<Boolean> byMethod = Optional.ofNullable(testClass.getCanonicalName())
							.flatMap(name -> methodName.flatMap(method -> listedAsHidden(name + "#" + method)));
					if (byMethod.isPresent()) {
						return byMethod.get();
					}
					for (Class<?> current = testClass; current != null; current = current.getEnclosingClass()) {
						Optional<Boolean> byClass = Optional.ofNullable(current.getCanonicalName())
								.flatMap(GeneratedHiddenTests::listedAsHidden);
						if (byClass.isPresent()) {
							return byClass.get();
						}
					}
					return @SETTINGS@.@UNLISTED@;
				}

				/**
				 * Which list names an entry exactly.
				 *
				 * @param entry the entry
				 * @return true for the hidden list, false for the public one, empty for neither
				 */
				private static Optional<Boolean> listedAsHidden(String entry) {
					if (HIDDEN.contains(entry)) {
						return Optional.of(true);
					}
					return PUBLIC.contains(entry) ? Optional.of(false) : Optional.empty();
				}
			}
			""";

	/** Source text of the sentinel test, before the placeholders are filled. */
	private static final String JUPITER_SENTINEL_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import org.junit.jupiter.api.Test;

			/**
			 * Generated by Ares. Fails when the generated hidden-test hook is not guarding
			 * this very run of this test, so a missing hook shows up as a red test instead
			 * of hidden tests running before the deadline.
			 */
			class GeneratedHiddenTestsSentinelTest {

				/** Checks that the generated hidden-test hook is guarding this run. */
				@Test
				void hiddenTestsAreActive() {
					if (!GeneratedHiddenTests.isGuarding(GeneratedHiddenTestsSentinelTest.class.getName() + "#hiddenTestsAreActive")) {
						throw new AssertionError(@MESSAGES@.localized("generated.hidden.tests.inactive"));
					}
				}
			}
			""";

	/** Prevents instantiation: this class only holds source texts. */
	private HiddenTestsSources() {
		throw new IllegalStateException("HiddenTestsSources is a utility class and should not be instantiated");
	}

	/**
	 * The JUnit extension's source.
	 *
	 * @param messagesClass   fully qualified name of the copied {@code Messages}.
	 * @param exercisePackage the exercise package Ares writes its generated
	 *                        security tests below.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterHook(@Nonnull String messagesClass, @Nonnull String exercisePackage) {
		return fill(JUPITER_HOOK_SOURCE, messagesClass).replace(EXERCISE_PACKAGE, exercisePackage);
	}

	/**
	 * The sentinel test's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterSentinel(@Nonnull String messagesClass) {
		return fill(JUPITER_SENTINEL_SOURCE, messagesClass);
	}

	/**
	 * Fills the placeholders of a source text.
	 *
	 * @param source        the source text with placeholders.
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text with every placeholder replaced
	 */
	@Nonnull
	private static String fill(@Nonnull String source, @Nonnull String messagesClass) {
		return source.replace(MESSAGES, messagesClass).replace(SETTINGS, TestBehaviorConfiguration.GENERATED_CLASS_NAME)
				.replace(DEADLINE, TestBehaviorConfiguration.HIDDEN_TESTS_DEADLINE_FIELD_NAME)
				.replace(ALWAYS_RUN_BEFORE, TestBehaviorConfiguration.HIDDEN_TESTS_ALWAYS_RUN_BEFORE_FIELD_NAME)
				.replace(HIDDEN, TestBehaviorConfiguration.HIDDEN_TESTS_LIST_FIELD_NAME)
				.replace(PUBLIC, TestBehaviorConfiguration.HIDDEN_TESTS_PUBLIC_LIST_FIELD_NAME)
				.replace(UNLISTED, TestBehaviorConfiguration.HIDDEN_TESTS_UNLISTED_FIELD_NAME)
				.replace("\n", System.lineSeparator());
	}
}
