package de.tum.cit.ase.ares.api.securitytest.java.writer;

import javax.annotation.Nonnull;

import de.tum.cit.ase.ares.api.policy.policySubComponents.TestBehaviorConfiguration;

/**
 * The Java source text of the hidden-test hook a precompile run writes into an
 * exercise. It holds back the tests the policy names until the deadline and
 * hides why they failed, as Ares does for {@code @HiddenTest} in postcompile,
 * so the schedule works without Ares at run time.
 *
 * @since 2.1.5
 * @author Luka Petrovic
 */
final class HiddenTestsSources {

	/** Simple name of the generated JUnit extension. */
	static final String JUPITER_HOOK = "GeneratedHiddenTests";

	/** Simple name of the generated sentinel test. */
	static final String JUPITER_SENTINEL = "GeneratedHiddenTestsSentinelTest";

	/** Placeholder for the copied {@code Messages} class in the source texts. */
	private static final String MESSAGES = "@MESSAGES@";

	/** Placeholder for the settings class in the source texts. */
	private static final String SETTINGS = "@SETTINGS@";

	/** Placeholder for the deadline field of the settings class. */
	private static final String DEADLINE = "@DEADLINE@";

	/** Placeholder for the always-run-before field of the settings class. */
	private static final String ALWAYS_RUN_BEFORE = "@ALWAYS_RUN_BEFORE@";

	/** Placeholder for the hidden-test list field of the settings class. */
	private static final String HIDDEN = "@HIDDEN@";

	/** Source text of the JUnit extension, before the placeholders are filled. */
	private static final String JUPITER_HOOK_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import java.lang.reflect.Method;
			import java.util.List;
			import java.util.Optional;
			import java.util.Set;
			import java.util.concurrent.ConcurrentHashMap;
			import java.util.function.Function;

			import org.junit.jupiter.api.extension.DynamicTestInvocationContext;
			import org.junit.jupiter.api.extension.ExtensionContext;
			import org.junit.jupiter.api.extension.InvocationInterceptor;
			import org.junit.jupiter.api.extension.ReflectiveInvocationContext;
			import org.opentest4j.AssertionFailedError;

			/**
			 * Generated by Ares. Holds back the hidden tests the policy names until the
			 * deadline and hides why they failed, as {@code @HiddenTest} does. Do not
			 * edit: regenerate instead.
			 */
			public final class GeneratedHiddenTests implements InvocationInterceptor {

				/** The hidden tests, as {@code pkg.Class} or {@code pkg.Class#method}. */
				private static final List<String> HIDDEN = List.of(@SETTINGS@.@HIDDEN@.split("\\n"));

				/** Every test this hook intercepted, as {@code class#method}; the sentinel checks it. */
				private static final Set<String> INTERCEPTED = ConcurrentHashMap.newKeySet();

				/**
				 * Whether this hook intercepted the given test in this test run.
				 *
				 * @param test the test, as {@code fully.qualified.Class#method}
				 * @return true once it was intercepted
				 */
				public static boolean intercepted(String test) {
					return INTERCEPTED.contains(test);
				}

				/**
				 * Guards a test method.
				 *
				 * @param invocation the method's invocation
				 * @param invocationContext the method and its arguments
				 * @param context the test's context
				 * @throws Throwable a hidden test's redacted failure, or the test's own
				 */
				@Override
				public void interceptTestMethod(Invocation<Void> invocation, ReflectiveInvocationContext<Method> invocationContext,
						ExtensionContext context) throws Throwable {
					guard(invocation, context);
				}

				/**
				 * Guards one invocation of a test template, such as a parameterised test.
				 *
				 * @param invocation the method's invocation
				 * @param invocationContext the method and its arguments
				 * @param context the test's context
				 * @throws Throwable a hidden test's redacted failure, or the test's own
				 */
				@Override
				public void interceptTestTemplateMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext context) throws Throwable {
					guard(invocation, context);
				}

				/**
				 * Guards a test factory.
				 *
				 * @param <T> the factory's result type
				 * @param invocation the factory's invocation
				 * @param invocationContext the factory and its arguments
				 * @param context the test's context
				 * @return the factory's result
				 * @throws Throwable a hidden test's redacted failure, or the test's own
				 */
				@Override
				public <T> T interceptTestFactoryMethod(Invocation<T> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext context) throws Throwable {
					return guard(invocation, context);
				}

				/**
				 * Guards a dynamic test, which counts as part of its factory.
				 *
				 * @param invocation the dynamic test's invocation
				 * @param invocationContext the dynamic test's context
				 * @param context the test's context
				 * @throws Throwable a hidden test's redacted failure, or the test's own
				 */
				@Override
				public void interceptDynamicTest(Invocation<Void> invocation, DynamicTestInvocationContext invocationContext,
						ExtensionContext context) throws Throwable {
					guard(invocation, context);
				}

				/**
				 * Records the test, then runs it unchanged unless the policy hides it; a
				 * hidden test runs only after the deadline or before the always-run-before
				 * date, and any failure it raises is replaced by a fixed text.
				 *
				 * @param <T> the invocation's result type
				 * @param invocation the invocation
				 * @param context the test's context
				 * @return the invocation's result
				 * @throws Throwable a hidden test's redacted failure, or the test's own
				 */
				private static <T> T guard(Invocation<T> invocation, ExtensionContext context) throws Throwable {
					Optional<String> methodName = nearest(context, ExtensionContext::getTestMethod).map(Method::getName);
					Optional<Class<?>> testClass = nearest(context, ExtensionContext::getTestClass);
					INTERCEPTED.add(testClass.map(Class::getName).orElse("") + "#" + methodName.orElse(""));
					if (testClass.isEmpty() || !isHidden(testClass.get(), methodName)) {
						return invocation.proceed();
					}
					long now = System.currentTimeMillis();
					if (now <= @SETTINGS@.@DEADLINE@ && now >= @SETTINGS@.@ALWAYS_RUN_BEFORE@) {
						invocation.skip();
						throw new AssertionFailedError(@MESSAGES@.localized("test_guard.hidden_test_before_deadline_message"));
					}
					try {
						return invocation.proceed();
					} catch (Throwable failure) {
						throw new AssertionError(@MESSAGES@.localized("test_guard.hidden_test_failed"));
					}
				}

				/**
				 * The nearest value up the context chain, so a dynamic test finds the
				 * method and class of the factory it belongs to.
				 *
				 * @param <T> the value's type
				 * @param context the test's context
				 * @param getter what to read from each context
				 * @return the value, if any context up the chain has one
				 */
				private static <T> Optional<T> nearest(ExtensionContext context,
						Function<ExtensionContext, Optional<T>> getter) {
					for (Optional<ExtensionContext> current = Optional.of(context); current.isPresent(); current = current.get()
							.getParent()) {
						Optional<T> value = getter.apply(current.get());
						if (value.isPresent()) {
							return value;
						}
					}
					return Optional.empty();
				}

				/**
				 * Whether the policy names the test's class, a class enclosing it, or that
				 * class with the test's method.
				 *
				 * @param testClass the test's class
				 * @param methodName the test's method, if any
				 * @return true when the test is hidden
				 */
				private static boolean isHidden(Class<?> testClass, Optional<String> methodName) {
					for (Class<?> current = testClass; current != null; current = current.getEnclosingClass()) {
						String className = current.getCanonicalName();
						if (className != null && (HIDDEN.contains(className)
								|| methodName.map(name -> HIDDEN.contains(className + "#" + name)).orElse(false))) {
							return true;
						}
					}
					return false;
				}
			}
			""";

	/** Source text of the sentinel test, before the placeholders are filled. */
	private static final String JUPITER_SENTINEL_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import org.junit.jupiter.api.Test;

			/**
			 * Generated by Ares. Fails when the generated hidden-test hook did not
			 * intercept this test, so a missing hook shows up as a red test instead of
			 * hidden tests running before the deadline.
			 */
			class GeneratedHiddenTestsSentinelTest {

				/** Checks that the generated hidden-test hook intercepted this test. */
				@Test
				void hiddenTestsAreActive() {
					if (!GeneratedHiddenTests.intercepted(GeneratedHiddenTestsSentinelTest.class.getName() + "#hiddenTestsAreActive")) {
						throw new AssertionError(@MESSAGES@.localized("generated.hidden.tests.inactive"));
					}
				}
			}
			""";

	/** Prevents instantiation: this class only holds source texts. */
	private HiddenTestsSources() {
		throw new IllegalStateException("HiddenTestsSources is a utility class and should not be instantiated");
	}

	/**
	 * The JUnit extension's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterHook(@Nonnull String messagesClass) {
		return fill(JUPITER_HOOK_SOURCE, messagesClass);
	}

	/**
	 * The sentinel test's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterSentinel(@Nonnull String messagesClass) {
		return fill(JUPITER_SENTINEL_SOURCE, messagesClass);
	}

	/**
	 * Fills the placeholders of a source text.
	 *
	 * @param source        the source text with placeholders.
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text with every placeholder replaced
	 */
	@Nonnull
	private static String fill(@Nonnull String source, @Nonnull String messagesClass) {
		return source.replace(MESSAGES, messagesClass).replace(SETTINGS, TestBehaviorConfiguration.GENERATED_CLASS_NAME)
				.replace(DEADLINE, TestBehaviorConfiguration.HIDDEN_TESTS_DEADLINE_FIELD_NAME)
				.replace(ALWAYS_RUN_BEFORE, TestBehaviorConfiguration.HIDDEN_TESTS_ALWAYS_RUN_BEFORE_FIELD_NAME)
				.replace(HIDDEN, TestBehaviorConfiguration.HIDDEN_TESTS_LIST_FIELD_NAME)
				.replace("\n", System.lineSeparator());
	}
}
