package de.tum.cit.ase.ares.api.securitytest.java.writer;

import javax.annotation.Nonnull;

import de.tum.cit.ase.ares.api.policy.policySubComponents.TestBehaviorConfiguration;

/**
 * The Java source text of the output-mirroring hook a precompile run writes
 * into an exercise. It gives a test's console output the echo and the limit the
 * policy sets, the way {@code IOTester} does in postcompile, so the setting
 * works without Ares at run time.
 *
 * @since 2.1.5
 * @author Luka Petrovic
 */
final class OutputMirroringSources {

	/** Simple name of the generated JUnit extension. */
	static final String JUPITER_HOOK = "GeneratedOutputMirroring";

	/** Simple name of the generated sentinel test. */
	static final String JUPITER_SENTINEL = "GeneratedOutputMirroringSentinelTest";

	/** Message key of the text the sentinel shows when the hook did not run. */
	static final String INACTIVE_KEY = "generated.output.mirroring.inactive";

	/** Placeholder for the copied {@code Messages} class in the source texts. */
	private static final String MESSAGES = "@MESSAGES@";

	/** Placeholder for the settings class in the source texts. */
	private static final String SETTINGS = "@SETTINGS@";

	/** Placeholder for the switch field of the settings class. */
	private static final String MIRRORED = "@MIRRORED@";

	/** Placeholder for the limit field of the settings class. */
	private static final String LIMIT = "@LIMIT@";

	/** Source text of the JUnit extension, before the placeholders are filled. */
	private static final String JUPITER_HOOK_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import java.io.ByteArrayOutputStream;
			import java.io.IOException;
			import java.io.OutputStream;
			import java.io.PrintStream;
			import java.nio.ByteBuffer;
			import java.nio.charset.CharacterCodingException;
			import java.nio.charset.CharsetDecoder;
			import java.nio.charset.CodingErrorAction;
			import java.nio.charset.StandardCharsets;

			import org.junit.jupiter.api.extension.AfterEachCallback;
			import org.junit.jupiter.api.extension.BeforeEachCallback;
			import org.junit.jupiter.api.extension.ExtensionContext;

			/**
			 * Generated by Ares. Gives a test's console output, from {@code @BeforeEach}
			 * to {@code @AfterEach}, the echo and the limit the policy sets, as
			 * {@code @MirrorOutput} does. Do not edit: regenerate instead.
			 */
			public final class GeneratedOutputMirroring implements BeforeEachCallback, AfterEachCallback {

				/** Where this hook remembers that it installed its streams for a test. */
				private static final ExtensionContext.Namespace NAMESPACE = ExtensionContext.Namespace
						.create(GeneratedOutputMirroring.class);

				/** Guards the installation, since the console streams are shared. */
				private static final Object LOCK = new Object();

				/** The console streams in place before the current test, while installed. */
				private static PrintStream originalOut;

				/** The error stream in place before the current test, while installed. */
				private static PrintStream originalErr;

				/** Whether this hook's streams are installed right now. */
				private static boolean installed;

				/** Set once the hook ran around a test; the sentinel checks it. */
				private static volatile boolean active;

				/** Records that the hook ran around a test. */
				private static void markActive() {
					active = true;
				}

				/**
				 * Whether the hook ran around a test in this test run, which includes the
				 * sentinel itself.
				 *
				 * @return true once the hook ran
				 */
				public static boolean isActive() {
					return active;
				}

				/**
				 * Replaces the console streams with bounded ones for this test, refusing a
				 * second installation while one is active.
				 *
				 * @param context the test's context
				 */
				@Override
				public void beforeEach(ExtensionContext context) {
					synchronized (LOCK) {
						if (installed) {
							throw new IllegalStateException(@MESSAGES@.localized("io_tester.already_installed"));
						}
						originalOut = System.out;
						originalErr = System.err;
						System.setOut(boundedOver(originalOut));
						System.setErr(boundedOver(originalErr));
						installed = true;
						context.getStore(NAMESPACE).put(GeneratedOutputMirroring.class, Boolean.TRUE);
					}
					markActive();
				}

				/**
				 * Restores the console streams this test's installation replaced, also when
				 * the test failed.
				 *
				 * @param context the test's context
				 */
				@Override
				public void afterEach(ExtensionContext context) {
					synchronized (LOCK) {
						if (context.getStore(NAMESPACE).remove(GeneratedOutputMirroring.class) == null) {
							return;
						}
						System.setOut(originalOut);
						System.setErr(originalErr);
						installed = false;
					}
				}

				/**
				 * A UTF-8 print stream over a bounded stream that echoes to the given stream
				 * when the policy mirrors output.
				 *
				 * @param original the stream in place before the test
				 * @return the replacement
				 */
				private static PrintStream boundedOver(PrintStream original) {
					OutputStream mirror = @SETTINGS@.@MIRRORED@ ? original : null;
					return new PrintStream(new BoundedStream(mirror, @SETTINGS@.@LIMIT@), true, StandardCharsets.UTF_8);
				}

				/**
				 * Counts what a test writes, refuses more than the limit, echoes it when
				 * mirroring is on, and refuses output that is not valid UTF-8, as Ares's own
				 * output capture does.
				 */
				static final class BoundedStream extends OutputStream {

					/** Where output is echoed, or null when it is not. */
					private final OutputStream mirror;

					/** The most bytes this stream accepts. */
					private final long limit;

					/** The bytes accepted so far. */
					private long count;

					/** Whether the test closed this stream. */
					private boolean closed;

					/** The bytes since the last flush, checked as UTF-8 on flush. */
					private final ByteArrayOutputStream pending = new ByteArrayOutputStream();

					/**
					 * Creates the stream.
					 *
					 * @param mirror where output is echoed, or null
					 * @param limit  the most bytes accepted
					 */
					BoundedStream(OutputStream mirror, long limit) {
						this.mirror = mirror;
						this.limit = limit;
					}

					/**
					 * Writes one byte.
					 *
					 * @param b the byte
					 * @throws IOException if the stream was closed
					 */
					@Override
					public synchronized void write(int b) throws IOException {
						accept(1);
						pending.write(b);
						if (mirror != null) {
							mirror.write(b);
						}
					}

					/**
					 * Writes part of an array.
					 *
					 * @param b      the bytes
					 * @param offset where to start
					 * @param length how many to write
					 * @throws IOException if the stream was closed
					 */
					@Override
					public synchronized void write(byte[] b, int offset, int length) throws IOException {
						accept(length);
						pending.write(b, offset, length);
						if (mirror != null) {
							mirror.write(b, offset, length);
						}
					}

					/**
					 * Checks that the bytes since the last flush are valid UTF-8.
					 *
					 * @throws IllegalArgumentException if they are not
					 */
					@Override
					public synchronized void flush() {
						byte[] bytes = pending.toByteArray();
						pending.reset();
						CharsetDecoder decoder = StandardCharsets.UTF_8.newDecoder()
								.onMalformedInput(CodingErrorAction.REPORT)
								.onUnmappableCharacter(CodingErrorAction.REPORT);
						try {
							decoder.decode(ByteBuffer.wrap(bytes));
						} catch (CharacterCodingException invalid) {
							throw new IllegalArgumentException(@MESSAGES@.localized("output_tester.output_is_invalid_utf8",
									new String(bytes, StandardCharsets.UTF_8)), invalid);
						}
					}

					/**
					 * Closes this stream; later writes fail. The real console stays open.
					 */
					@Override
					public synchronized void close() {
						closed = true;
					}

					/**
					 * Counts new bytes, refusing them after a close or beyond the limit.
					 *
					 * @param newBytes how many bytes are about to be written
					 * @throws IOException if the stream was closed
					 */
					private void accept(int newBytes) throws IOException {
						if (closed) {
							throw new IOException(@MESSAGES@.localized("output_tester.output_closed"));
						}
						count += newBytes;
						if (count > limit) {
							throw new SecurityException(@MESSAGES@.localized("output_tester.output_maxExceeded", count));
						}
					}
				}
			}
			""";

	/** Source text of the sentinel test, before the placeholders are filled. */
	private static final String JUPITER_SENTINEL_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import org.junit.jupiter.api.Test;

			/**
			 * Generated by Ares. Fails when the generated output mirroring did not run
			 * around this test, so a missing hook shows up as a red test instead of
			 * unlimited output.
			 */
			class GeneratedOutputMirroringSentinelTest {

				/** Checks that the generated output mirroring ran around this test. */
				@Test
				void outputMirroringIsActive() {
					if (!GeneratedOutputMirroring.isActive()) {
						throw new AssertionError(@MESSAGES@.localized("generated.output.mirroring.inactive"));
					}
				}
			}
			""";

	/** Prevents instantiation: this class only holds source texts. */
	private OutputMirroringSources() {
		throw new IllegalStateException("OutputMirroringSources is a utility class and should not be instantiated");
	}

	/**
	 * The JUnit extension's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterHook(@Nonnull String messagesClass) {
		return fill(JUPITER_HOOK_SOURCE, messagesClass);
	}

	/**
	 * The sentinel test's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterSentinel(@Nonnull String messagesClass) {
		return fill(JUPITER_SENTINEL_SOURCE, messagesClass);
	}

	/**
	 * Fills the placeholders of a source text.
	 *
	 * @param source        the source text with placeholders.
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text with every placeholder replaced
	 */
	@Nonnull
	private static String fill(@Nonnull String source, @Nonnull String messagesClass) {
		return source.replace(MESSAGES, messagesClass).replace(SETTINGS, TestBehaviorConfiguration.GENERATED_CLASS_NAME)
				.replace(MIRRORED, TestBehaviorConfiguration.OUTPUT_MIRRORING_MIRRORED_FIELD_NAME)
				.replace(LIMIT, TestBehaviorConfiguration.OUTPUT_MIRRORING_LIMIT_FIELD_NAME)
				.replace("\n", System.lineSeparator());
	}
}
