package de.tum.cit.ase.ares.api.securitytest.java.writer;

import javax.annotation.Nonnull;

import de.tum.cit.ase.ares.api.policy.policySubComponents.TestBehaviorConfiguration;

/**
 * The Java source text of the strict-timeout hooks a precompile run writes into
 * an exercise. They bound every test by the policy's timeout the way
 * {@code @StrictTimeout} does, so the setting works without Ares at run time.
 * Generated as text, so no class-path resource can stand in for them.
 *
 * @since 2.1.5
 * @author Luka Petrovic
 */
final class StrictTimeoutSources {

	/** Simple name of the generated JUnit Jupiter interceptor. */
	static final String JUPITER_HOOK = "GeneratedStrictTimeout";

	/** Simple name of the generated jqwik lifecycle hook. */
	static final String JQWIK_HOOK = "GeneratedJqwikStrictTimeout";

	/** Simple name of the generated JUnit sentinel test. */
	static final String JUPITER_SENTINEL = "GeneratedStrictTimeoutSentinelTest";

	/** Simple name of the generated jqwik sentinel test. */
	static final String JQWIK_SENTINEL = "GeneratedJqwikStrictTimeoutSentinelTest";

	/** Message key of the text a sentinel shows when its hook did not time it. */
	static final String INACTIVE_KEY = "generated.strict.timeout.inactive";

	/** Message key of the text shown when jqwik is present but not covered. */
	static final String JQWIK_MISSING_KEY = "generated.strict.timeout.jqwik.missing";

	/** Message key of the text shown when jqwik's engine cannot be reached. */
	static final String ENGINE_MISSING_KEY = "generated.strict.timeout.jqwik.engine.missing";

	/** Placeholder for the copied {@code Messages} class in the source texts. */
	private static final String MESSAGES = "@MESSAGES@";

	/** Placeholder for the settings class in the source texts. */
	private static final String SETTINGS = "@SETTINGS@";

	/** Placeholder for the timeout field of the settings class. */
	private static final String TIMEOUT = "@TIMEOUT@";

	/** Placeholder for the timeout unit field of the settings class. */
	private static final String UNIT = "@UNIT@";

	/** Placeholder for the grace field of the settings class. */
	private static final String GRACE = "@GRACE@";

	/** Placeholder for the grace unit field of the settings class. */
	private static final String GRACE_UNIT = "@GRACE_UNIT@";

	/** Placeholder for whether the jqwik hook was generated beside the sentinel. */
	private static final String JQWIK_GENERATED = "@JQWIK_GENERATED@";

	/**
	 * Source text of the JUnit Jupiter interceptor, before the placeholders are
	 * filled.
	 */
	private static final String JUPITER_HOOK_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import java.lang.reflect.Constructor;
			import java.lang.reflect.Method;
			import java.time.Duration;
			import java.util.ArrayList;
			import java.util.List;
			import java.util.concurrent.ExecutionException;
			import java.util.concurrent.ExecutorService;
			import java.util.concurrent.Executors;
			import java.util.concurrent.Future;
			import java.util.concurrent.ThreadFactory;
			import java.util.concurrent.TimeUnit;
			import java.util.concurrent.TimeoutException;
			import java.util.concurrent.atomic.AtomicInteger;

			import org.junit.jupiter.api.extension.DynamicTestInvocationContext;
			import org.junit.jupiter.api.extension.ExtensionContext;
			import org.junit.jupiter.api.extension.InvocationInterceptor;
			import org.junit.jupiter.api.extension.ReflectiveInvocationContext;

			/**
			 * Generated by Ares. Stops every test, setup and teardown that runs longer than
			 * the policy's strict timeout, as {@code @StrictTimeout} does. Do not edit:
			 * regenerate instead.
			 */
			public final class GeneratedStrictTimeout implements InvocationInterceptor {

				/** The grace period a JUnit invocation gets when the policy names none. */
				private static final Duration DEFAULT_GRACE = Duration.ofMillis(50);

				/** The exit code of a test process halted because a worker did not stop. */
				private static final int UNRESPONSIVE_EXIT_CODE = 124;

				/** Set once a test method ran under this interceptor; the sentinel checks it. */
				private static volatile boolean active;

				/** Records that a test method ran under this interceptor. */
				private static void markActive() {
					active = true;
				}

				/**
				 * Whether a test method ran under this interceptor in this test run, which
				 * includes the sentinel itself.
				 *
				 * @return true once a test method was timed
				 */
				public static boolean isActive() {
					return active;
				}

				/**
				 * Times the creation of the test class.
				 *
				 * @param <T>               the test class
				 * @param invocation        creates the test instance
				 * @param invocationContext the constructor call
				 * @param extensionContext  the test class's context
				 * @return the test instance
				 * @throws Throwable whatever creating it threw, or the timeout
				 */
				@Override
				public <T> T interceptTestClassConstructor(Invocation<T> invocation,
						ReflectiveInvocationContext<Constructor<T>> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					return executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times a {@code @BeforeAll} method.
				 *
				 * @param invocation        runs the method
				 * @param invocationContext the method call
				 * @param extensionContext  the method's context
				 * @throws Throwable whatever the method threw, or the timeout
				 */
				@Override
				public void interceptBeforeAllMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times a {@code @BeforeEach} method.
				 *
				 * @param invocation        runs the method
				 * @param invocationContext the method call
				 * @param extensionContext  the method's context
				 * @throws Throwable whatever the method threw, or the timeout
				 */
				@Override
				public void interceptBeforeEachMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times a test method.
				 *
				 * @param invocation        runs the method
				 * @param invocationContext the method call
				 * @param extensionContext  the method's context
				 * @throws Throwable whatever the method threw, or the timeout
				 */
				@Override
				public void interceptTestMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					markActive();
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times a test factory.
				 *
				 * @param <T>               the factory's return type
				 * @param invocation        runs the factory
				 * @param invocationContext the factory call
				 * @param extensionContext  the factory's context
				 * @return the factory's tests
				 * @throws Throwable whatever the factory threw, or the timeout
				 */
				@Override
				public <T> T interceptTestFactoryMethod(Invocation<T> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					return executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times one invocation of a test template, such as a parameterised test.
				 *
				 * @param invocation        runs the invocation
				 * @param invocationContext the method call
				 * @param extensionContext  the invocation's context
				 * @throws Throwable whatever the invocation threw, or the timeout
				 */
				@Override
				public void interceptTestTemplateMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times a dynamic test.
				 *
				 * @param invocation        runs the dynamic test
				 * @param invocationContext the dynamic test's invocation
				 * @param extensionContext  the dynamic test's context
				 * @throws Throwable whatever the test threw, or the timeout
				 */
				@Override
				public void interceptDynamicTest(Invocation<Void> invocation, DynamicTestInvocationContext invocationContext,
						ExtensionContext extensionContext) throws Throwable {
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times an {@code @AfterEach} method.
				 *
				 * @param invocation        runs the method
				 * @param invocationContext the method call
				 * @param extensionContext  the method's context
				 * @throws Throwable whatever the method threw, or the timeout
				 */
				@Override
				public void interceptAfterEachMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times an {@code @AfterAll} method.
				 *
				 * @param invocation        runs the method
				 * @param invocationContext the method call
				 * @param extensionContext  the method's context
				 * @throws Throwable whatever the method threw, or the timeout
				 */
				@Override
				public void interceptAfterAllMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Runs an action on a worker thread and stops it after the policy's timeout.
				 * A worker that does not stop within the grace period halts the test process,
				 * since it would otherwise keep running untrusted code. The thread-creation
				 * check exempts exactly this method, by name.
				 *
				 * @param <T>          the action's result
				 * @param action       the action to bound
				 * @param defaultGrace the grace period when the policy names none
				 * @return the action's result
				 * @throws Throwable whatever the action threw, or a timeout naming the limit
				 */
				public static <T> T executeWithTimeout(TimedAction<T> action, Duration defaultGrace) throws Throwable {
					Duration timeout = timeout();
					long graceNanos = graceNanos(defaultGrace);
					ExecutorService executor = Executors.newSingleThreadExecutor(new WorkerFactory());
					Future<T> future = executor.submit(() -> call(action));
					try {
						return future.get(timeout.toMillis(), TimeUnit.MILLISECONDS);
					} catch (ExecutionException failure) {
						throw unwrapped(failure);
					} catch (TimeoutException expired) {
						terminate(future, executor, graceNanos);
						throw new TimeoutException(@MESSAGES@.localized("timeout.failure_message", format(timeout)));
					} finally {
						executor.shutdownNow();
					}
				}

				/**
				 * The policy's timeout.
				 *
				 * @return the timeout
				 */
				static Duration timeout() {
					return Duration.of(@SETTINGS@.@TIMEOUT@, TimeUnit.valueOf(@SETTINGS@.@UNIT@).toChronoUnit());
				}

				/**
				 * The policy's grace period in nanoseconds, or the caller's default.
				 *
				 * @param defaultGrace the caller's default
				 * @return the grace period in nanoseconds
				 */
				static long graceNanos(Duration defaultGrace) {
					if (@SETTINGS@.@GRACE@ < 0) {
						return defaultGrace.toNanos();
					}
					return Duration.of(@SETTINGS@.@GRACE@, TimeUnit.valueOf(@SETTINGS@.@GRACE_UNIT@).toChronoUnit())
							.toNanos();
				}

				/**
				 * Runs the action, passing on what a worker may throw.
				 *
				 * @param <T>    the action's result
				 * @param action the action
				 * @return the action's result
				 * @throws Exception whatever the action threw, wrapped if it is neither an
				 *                   exception nor an error
				 */
				private static <T> T call(TimedAction<T> action) throws Exception {
					try {
						return action.run();
					} catch (Exception | Error failure) {
						throw failure;
					} catch (Throwable other) {
						throw new ExecutionException(other);
					}
				}

				/**
				 * The failure the action threw, without the worker's wrapping.
				 *
				 * @param failure the worker's failure
				 * @return what the action threw
				 */
				private static Throwable unwrapped(ExecutionException failure) {
					Throwable cause = failure.getCause();
					if (cause instanceof ExecutionException wrapped && wrapped.getCause() != null) {
						return wrapped.getCause();
					}
					return cause;
				}

				/**
				 * Interrupts the worker and waits the grace period for it to stop, halting
				 * the test process if it does not.
				 *
				 * @param future     the worker's task
				 * @param executor   the worker's executor
				 * @param graceNanos the grace period in nanoseconds
				 */
				private static void terminate(Future<?> future, ExecutorService executor, long graceNanos) {
					executor.shutdown();
					future.cancel(true);
					if (!awaitTermination(executor, graceNanos)) {
						Runtime.getRuntime().halt(UNRESPONSIVE_EXIT_CODE);
						throw new AssertionError("Halting the test process returned without halting it");
					}
				}

				/**
				 * Waits for the executor to stop, at most the given time, keeping an
				 * interruption for the caller.
				 *
				 * @param executor     the executor
				 * @param timeoutNanos the longest wait in nanoseconds
				 * @return true when it stopped in time
				 */
				private static boolean awaitTermination(ExecutorService executor, long timeoutNanos) {
					long deadline = System.nanoTime() + timeoutNanos;
					boolean interrupted = false;
					try {
						while (!executor.isTerminated()) {
							long remainingNanos = deadline - System.nanoTime();
							if (remainingNanos <= 0) {
								return false;
							}
							try {
								if (executor.awaitTermination(remainingNanos, TimeUnit.NANOSECONDS)) {
									return true;
								}
							} catch (InterruptedException ignored) {
								interrupted = true;
							}
						}
						return true;
					} finally {
						if (interrupted) {
							Thread.currentThread().interrupt();
						}
					}
				}

				/**
				 * A duration in hours, minutes, seconds and milliseconds, as
				 * {@code @StrictTimeout} reports it.
				 *
				 * @param duration the duration
				 * @return the formatted duration
				 */
				private static String format(Duration duration) {
					List<String> parts = new ArrayList<>();
					long hours = duration.toHours();
					if (hours != 0) {
						parts.add(hours + " h");
					}
					if (duration.toMinutesPart() != 0) {
						parts.add(duration.toMinutesPart() + " min");
					}
					if (duration.toSecondsPart() != 0) {
						parts.add(duration.toSecondsPart() + " s");
					}
					if (duration.toMillisPart() != 0) {
						parts.add(duration.toMillisPart() + " ms");
					}
					return String.join(" ", parts);
				}

				/**
				 * An action that may throw anything, as a JUnit invocation may.
				 *
				 * @param <T> the action's result
				 */
				@FunctionalInterface
				public interface TimedAction<T> {

					/**
					 * Runs the action.
					 *
					 * @return its result
					 * @throws Throwable whatever it throws
					 */
					T run() throws Throwable;
				}

				/**
				 * Creates the timeout's worker threads. A class of its own, so the
				 * thread-creation check finds {@code executeWithTimeout} as the first frame
				 * of {@code GeneratedStrictTimeout} itself.
				 */
				static final class WorkerFactory implements ThreadFactory {

					/** Numbers the worker threads. */
					private static final AtomicInteger WORKER_ID = new AtomicInteger(1);

					/**
					 * Creates a daemon worker thread.
					 *
					 * @param runnable the work
					 * @return the thread
					 */
					@Override
					public Thread newThread(Runnable runnable) {
						Thread thread = new Thread(runnable, "ares-generated-timeout-" + WORKER_ID.getAndIncrement());
						thread.setDaemon(true);
						thread.setPriority(Thread.NORM_PRIORITY);
						return thread;
					}
				}
			}
			""";

	/** Source text of the jqwik hook, before the placeholders are filled. */
	private static final String JQWIK_HOOK_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import java.lang.reflect.InvocationTargetException;
			import java.lang.reflect.Method;
			import java.time.Duration;
			import java.util.List;
			import java.util.function.Supplier;

			import net.jqwik.api.lifecycle.AroundTryHook;
			import net.jqwik.api.lifecycle.PropagationMode;
			import net.jqwik.api.lifecycle.TryExecutionResult;
			import net.jqwik.api.lifecycle.TryExecutor;
			import net.jqwik.api.lifecycle.TryLifecycleContext;

			/**
			 * Generated by Ares. Stops every jqwik try that runs longer than the policy's
			 * strict timeout, as {@code @StrictTimeout} does. Do not edit: regenerate
			 * instead.
			 */
			public final class GeneratedJqwikStrictTimeout implements AroundTryHook {

				/** The grace period a jqwik try gets when the policy names none. */
				private static final Duration DEFAULT_GRACE = Duration.ofSeconds(1);

				/** Set once this hook has timed a try; the sentinel checks it. */
				private static volatile boolean active;

				/** Records that this hook timed a try. */
				private static void markActive() {
					active = true;
				}

				/**
				 * Whether this hook has timed a try in this test run, which includes the
				 * sentinel itself.
				 *
				 * @return true once a try was timed
				 */
				public static boolean isActive() {
					return active;
				}

				/**
				 * Applies this hook to every property, not only to the container jqwik
				 * registers it on.
				 *
				 * @return every descendant
				 */
				@Override
				public PropagationMode propagateTo() {
					return PropagationMode.ALL_DESCENDANTS;
				}

				/**
				 * Keeps the timeout inside jqwik's try lifecycle, as Ares's own jqwik timeout
				 * does: setup and cleanup must stay on jqwik's own thread.
				 *
				 * @return the proximity Ares's jqwik timeout uses
				 */
				@Override
				public int aroundTryProximity() {
					return 40;
				}

				/**
				 * Runs one try on a worker thread, bounded by the policy's timeout, with
				 * jqwik's engine state handed over to the worker.
				 *
				 * @param context    the try's context
				 * @param aTry       runs the try
				 * @param parameters the try's parameters
				 * @return the try's result
				 * @throws Throwable whatever the try threw, or the timeout
				 */
				@Override
				public TryExecutionResult aroundTry(TryLifecycleContext context, TryExecutor aTry, List<Object> parameters)
						throws Throwable {
					markActive();
					EngineState state = EngineState.capture();
					return GeneratedStrictTimeout.executeWithTimeout(() -> state.runWith(() -> aTry.execute(parameters)),
							DEFAULT_GRACE);
				}

				/**
				 * jqwik's per-thread engine state, reached by reflection, because jqwik's
				 * engine is only on the run-time class path of an exercise.
				 */
				static final class EngineState {

					/** jqwik's holder of the current domain context. */
					private static final String DOMAIN_CONTEXT = "net.jqwik.engine.execution.lifecycle.CurrentDomainContext";

					/** jqwik's holder of the current test descriptor. */
					private static final String TEST_DESCRIPTOR = "net.jqwik.engine.execution.lifecycle.CurrentTestDescriptor";

					/** The domain context of the calling thread. */
					private final Object domainContext;

					/** The test descriptor of the calling thread. */
					private final Object testDescriptor;

					/** Runs a supplier with a domain context set. */
					private final Method runWithContext;

					/** Runs a supplier with a test descriptor set. */
					private final Method runWithDescriptor;

					/**
					 * Holds the captured state.
					 *
					 * @param domainContext     the domain context
					 * @param testDescriptor    the test descriptor
					 * @param runWithContext    jqwik's method setting a domain context
					 * @param runWithDescriptor jqwik's method setting a test descriptor
					 */
					private EngineState(Object domainContext, Object testDescriptor, Method runWithContext,
							Method runWithDescriptor) {
						this.domainContext = domainContext;
						this.testDescriptor = testDescriptor;
						this.runWithContext = runWithContext;
						this.runWithDescriptor = runWithDescriptor;
					}

					/**
					 * Captures the calling thread's engine state.
					 *
					 * @return the state
					 * @throws AssertionError naming jqwik's engine when it cannot be reached
					 */
					static EngineState capture() {
						try {
							ClassLoader loader = GeneratedJqwikStrictTimeout.class.getClassLoader();
							Class<?> domainHolder = Class.forName(DOMAIN_CONTEXT, true, loader);
							Class<?> descriptorHolder = Class.forName(TEST_DESCRIPTOR, true, loader);
							Method runWithContext = findStatic(domainHolder, "runWithContext");
							Method runWithDescriptor = findStatic(descriptorHolder, "runWithDescriptor");
							return new EngineState(domainHolder.getMethod("get").invoke(null),
									descriptorHolder.getMethod("get").invoke(null), runWithContext, runWithDescriptor);
						} catch (ReflectiveOperationException | LinkageError missing) {
							throw new AssertionError(@MESSAGES@.localized("generated.strict.timeout.jqwik.engine.missing"),
									missing);
						}
					}

					/**
					 * Runs the body with the captured state set on the current thread.
					 *
					 * @param <T>  the body's result
					 * @param body the body
					 * @return the body's result
					 * @throws Throwable whatever the body threw
					 */
					@SuppressWarnings("unchecked")
					<T> T runWith(Supplier<T> body) throws Throwable {
						Supplier<Object> withDescriptor = () -> invokeUnchecked(runWithDescriptor, testDescriptor, body);
						return (T) invoke(runWithContext, domainContext, withDescriptor);
					}

					/**
					 * The public static two-argument method of that name.
					 *
					 * @param holder the class declaring it
					 * @param name   the method's name
					 * @return the method
					 * @throws NoSuchMethodException if there is none
					 */
					private static Method findStatic(Class<?> holder, String name) throws NoSuchMethodException {
						for (Method method : holder.getMethods()) {
							if (method.getName().equals(name) && method.getParameterCount() == 2) {
								return method;
							}
						}
						throw new NoSuchMethodException(holder.getName() + "." + name);
					}

					/**
					 * Calls a static method, passing on what it throws.
					 *
					 * @param method   the method
					 * @param state    its first argument
					 * @param supplier its second argument
					 * @return its result
					 * @throws Throwable whatever it threw
					 */
					private static Object invoke(Method method, Object state, Supplier<?> supplier) throws Throwable {
						try {
							return method.invoke(null, state, supplier);
						} catch (InvocationTargetException thrown) {
							throw thrown.getCause();
						}
					}

					/**
					 * Calls a static method from inside a supplier, passing on what it throws
					 * without declaring it.
					 *
					 * @param method   the method
					 * @param state    its first argument
					 * @param supplier its second argument
					 * @return its result
					 */
					private static Object invokeUnchecked(Method method, Object state, Supplier<?> supplier) {
						try {
							return invoke(method, state, supplier);
						} catch (Throwable thrown) {
							throw EngineState.<RuntimeException>rethrow(thrown);
						}
					}

					/**
					 * Throws any throwable without declaring it.
					 *
					 * @param <E>       the type the compiler is told is thrown
					 * @param throwable the throwable
					 * @return never returns
					 * @throws E always
					 */
					@SuppressWarnings("unchecked")
					private static <E extends Throwable> RuntimeException rethrow(Throwable throwable) throws E {
						throw (E) throwable;
					}
				}
			}
			""";

	/**
	 * Source text of the JUnit sentinel test, before the placeholders are filled.
	 */
	private static final String JUPITER_SENTINEL_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import org.junit.jupiter.api.Test;

			/**
			 * Generated by Ares. Fails when the generated strict timeout did not time this
			 * test, or when jqwik is present without its hook, so a missing hook shows up
			 * as a red test instead of unbounded tests.
			 */
			class GeneratedStrictTimeoutSentinelTest {

				/** Whether the generator wrote the jqwik hook beside this test. */
				private static final boolean JQWIK_HOOK_GENERATED = @JQWIK_GENERATED@;

				/** Checks that the generated strict timeout timed this test. */
				@Test
				void strictTimeoutIsActive() {
					if (!GeneratedStrictTimeout.isActive()) {
						throw new AssertionError(@MESSAGES@.localized("generated.strict.timeout.inactive"));
					}
				}

				/** Checks that jqwik, when the test run has it, got its hook as well. */
				@Test
				void jqwikIsCoveredWhenPresent() {
					if (!JQWIK_HOOK_GENERATED && jqwikIsPresent()) {
						throw new AssertionError(@MESSAGES@.localized("generated.strict.timeout.jqwik.missing"));
					}
				}

				/**
				 * Whether jqwik's hook interface is on this test run's class path.
				 *
				 * @return true when jqwik can run properties here
				 */
				private static boolean jqwikIsPresent() {
					try {
						Class.forName("net.jqwik.api.lifecycle.AroundTryHook", false,
								GeneratedStrictTimeoutSentinelTest.class.getClassLoader());
						return true;
					} catch (ClassNotFoundException absent) {
						return false;
					}
				}
			}
			""";

	/**
	 * Source text of the jqwik sentinel test, before the placeholders are filled.
	 */
	private static final String JQWIK_SENTINEL_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import net.jqwik.api.Example;

			/**
			 * Generated by Ares. Fails when the generated jqwik strict timeout did not
			 * time this property, so a missing hook shows up as a red test instead of
			 * unbounded properties.
			 */
			class GeneratedJqwikStrictTimeoutSentinelTest {

				/** Checks that the generated jqwik strict timeout timed this property. */
				@Example
				void strictTimeoutIsActive() {
					if (!GeneratedJqwikStrictTimeout.isActive()) {
						throw new AssertionError(@MESSAGES@.localized("generated.strict.timeout.inactive"));
					}
				}
			}
			""";

	/** Prevents instantiation: this class only holds source texts. */
	private StrictTimeoutSources() {
		throw new IllegalStateException("StrictTimeoutSources is a utility class and should not be instantiated");
	}

	/**
	 * The JUnit Jupiter interceptor's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterHook(@Nonnull String messagesClass) {
		return fill(JUPITER_HOOK_SOURCE, messagesClass);
	}

	/**
	 * The jqwik hook's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jqwikHook(@Nonnull String messagesClass) {
		return fill(JQWIK_HOOK_SOURCE, messagesClass);
	}

	/**
	 * The JUnit sentinel test's source.
	 *
	 * @param messagesClass      fully qualified name of the copied
	 *                           {@code Messages}.
	 * @param jqwikHookGenerated whether the jqwik hook is generated beside it.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterSentinel(@Nonnull String messagesClass, boolean jqwikHookGenerated) {
		return fill(JUPITER_SENTINEL_SOURCE, messagesClass).replace(JQWIK_GENERATED,
				String.valueOf(jqwikHookGenerated));
	}

	/**
	 * The jqwik sentinel test's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jqwikSentinel(@Nonnull String messagesClass) {
		return fill(JQWIK_SENTINEL_SOURCE, messagesClass);
	}

	/**
	 * Fills the placeholders of a source text.
	 *
	 * @param source        the source text with placeholders.
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text with every placeholder but the jqwik flag replaced
	 */
	@Nonnull
	private static String fill(@Nonnull String source, @Nonnull String messagesClass) {
		return source.replace(MESSAGES, messagesClass).replace(SETTINGS, TestBehaviorConfiguration.GENERATED_CLASS_NAME)
				.replace(GRACE_UNIT, TestBehaviorConfiguration.STRICT_TIMEOUTS_GRACE_UNIT_FIELD_NAME)
				.replace(GRACE, TestBehaviorConfiguration.STRICT_TIMEOUTS_GRACE_FIELD_NAME)
				.replace(TIMEOUT, TestBehaviorConfiguration.STRICT_TIMEOUTS_TIMEOUT_FIELD_NAME)
				.replace(UNIT, TestBehaviorConfiguration.STRICT_TIMEOUTS_TIME_UNIT_FIELD_NAME)
				.replace("\n", System.lineSeparator());
	}
}
