package de.tum.cit.ase.ares.api.securitytest.java.writer;

import javax.annotation.Nonnull;

import de.tum.cit.ase.ares.api.policy.policySubComponents.TestBehaviorConfiguration;

/**
 * The Java source text of the strict-timeout hooks a precompile run writes into
 * an exercise. They bound every test by the policy's timeout the way
 * {@code @StrictTimeout} does, so the setting works without Ares at run time.
 * Generated as text, so no class-path resource can stand in for them.
 *
 * @since 2.1.5
 * @author Luka Petrovic
 */
final class StrictTimeoutSources {

	/** Simple name of the generated JUnit Jupiter interceptor. */
	static final String JUPITER_HOOK = "GeneratedStrictTimeout";

	/** Simple name of the generated JUnit sentinel test. */
	static final String JUPITER_SENTINEL = "GeneratedStrictTimeoutSentinelTest";

	/** Message key of the text a sentinel shows when its hook did not time it. */
	static final String INACTIVE_KEY = "generated.strict.timeout.inactive";

	/** Placeholder for the copied {@code Messages} class in the source texts. */
	private static final String MESSAGES = "@MESSAGES@";

	/** Placeholder for the settings class in the source texts. */
	private static final String SETTINGS = "@SETTINGS@";

	/** Placeholder for the timeout field of the settings class. */
	private static final String TIMEOUT = "@TIMEOUT@";

	/** Placeholder for the timeout unit field of the settings class. */
	private static final String UNIT = "@UNIT@";

	/** Placeholder for the grace field of the settings class. */
	private static final String GRACE = "@GRACE@";

	/** Placeholder for the grace unit field of the settings class. */
	private static final String GRACE_UNIT = "@GRACE_UNIT@";

	/**
	 * Source text of the JUnit Jupiter interceptor, before the placeholders are
	 * filled.
	 */
	private static final String JUPITER_HOOK_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import java.lang.reflect.Constructor;
			import java.lang.reflect.Method;
			import java.time.Duration;
			import java.util.ArrayList;
			import java.util.List;
			import java.util.concurrent.ExecutionException;
			import java.util.concurrent.ExecutorService;
			import java.util.concurrent.Executors;
			import java.util.concurrent.Future;
			import java.util.concurrent.ThreadFactory;
			import java.util.concurrent.TimeUnit;
			import java.util.concurrent.TimeoutException;
			import java.util.concurrent.atomic.AtomicInteger;

			import org.junit.jupiter.api.extension.DynamicTestInvocationContext;
			import org.junit.jupiter.api.extension.ExtensionContext;
			import org.junit.jupiter.api.extension.InvocationInterceptor;
			import org.junit.jupiter.api.extension.ReflectiveInvocationContext;

			/**
			 * Generated by Ares. Stops every test, setup and teardown that runs longer than
			 * the policy's strict timeout, as {@code @StrictTimeout} does. Do not edit:
			 * regenerate instead.
			 */
			public final class GeneratedStrictTimeout implements InvocationInterceptor {

				/** The grace period a JUnit invocation gets when the policy names none. */
				private static final Duration DEFAULT_GRACE = Duration.ofMillis(50);

				/** The exit code of a test process halted because a worker did not stop. */
				private static final int UNRESPONSIVE_EXIT_CODE = 124;

				/** The test guarded now, inherited by a worker another hook starts. */
				private static final InheritableThreadLocal<String> GUARDING = new InheritableThreadLocal<>();

				/**
				 * Whether this hook is guarding the named test in this invocation.
				 *
				 * @param test the test, as {@code fully.qualified.Class#method}
				 * @return true while that test runs inside this hook
				 */
				public static boolean isGuarding(String test) {
					return test.equals(GUARDING.get());
				}

				/**
				 * Times the creation of the test class.
				 *
				 * @param <T>               the test class
				 * @param invocation        creates the test instance
				 * @param invocationContext the constructor call
				 * @param extensionContext  the test class's context
				 * @return the test instance
				 * @throws Throwable whatever creating it threw, or the timeout
				 */
				@Override
				public <T> T interceptTestClassConstructor(Invocation<T> invocation,
						ReflectiveInvocationContext<Constructor<T>> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					return executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times a {@code @BeforeAll} method.
				 *
				 * @param invocation        runs the method
				 * @param invocationContext the method call
				 * @param extensionContext  the method's context
				 * @throws Throwable whatever the method threw, or the timeout
				 */
				@Override
				public void interceptBeforeAllMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times a {@code @BeforeEach} method.
				 *
				 * @param invocation        runs the method
				 * @param invocationContext the method call
				 * @param extensionContext  the method's context
				 * @throws Throwable whatever the method threw, or the timeout
				 */
				@Override
				public void interceptBeforeEachMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times a test method.
				 *
				 * @param invocation        runs the method
				 * @param invocationContext the method call
				 * @param extensionContext  the method's context
				 * @throws Throwable whatever the method threw, or the timeout
				 */
				@Override
				public void interceptTestMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					executeWithTimeout(() -> {
						GUARDING.set(extensionContext.getRequiredTestClass().getName() + "#" +
								extensionContext.getRequiredTestMethod().getName());
						try {
							invocation.proceed();
							return null;
						} finally {
							GUARDING.remove();
						}
					}, DEFAULT_GRACE);
				}

				/**
				 * Times a test factory.
				 *
				 * @param <T>               the factory's return type
				 * @param invocation        runs the factory
				 * @param invocationContext the factory call
				 * @param extensionContext  the factory's context
				 * @return the factory's tests
				 * @throws Throwable whatever the factory threw, or the timeout
				 */
				@Override
				public <T> T interceptTestFactoryMethod(Invocation<T> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					return executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times one invocation of a test template, such as a parameterised test.
				 *
				 * @param invocation        runs the invocation
				 * @param invocationContext the method call
				 * @param extensionContext  the invocation's context
				 * @throws Throwable whatever the invocation threw, or the timeout
				 */
				@Override
				public void interceptTestTemplateMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times a dynamic test.
				 *
				 * @param invocation        runs the dynamic test
				 * @param invocationContext the dynamic test's invocation
				 * @param extensionContext  the dynamic test's context
				 * @throws Throwable whatever the test threw, or the timeout
				 */
				@Override
				public void interceptDynamicTest(Invocation<Void> invocation, DynamicTestInvocationContext invocationContext,
						ExtensionContext extensionContext) throws Throwable {
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times an {@code @AfterEach} method.
				 *
				 * @param invocation        runs the method
				 * @param invocationContext the method call
				 * @param extensionContext  the method's context
				 * @throws Throwable whatever the method threw, or the timeout
				 */
				@Override
				public void interceptAfterEachMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Times an {@code @AfterAll} method.
				 *
				 * @param invocation        runs the method
				 * @param invocationContext the method call
				 * @param extensionContext  the method's context
				 * @throws Throwable whatever the method threw, or the timeout
				 */
				@Override
				public void interceptAfterAllMethod(Invocation<Void> invocation,
						ReflectiveInvocationContext<Method> invocationContext, ExtensionContext extensionContext)
						throws Throwable {
					executeWithTimeout(invocation::proceed, DEFAULT_GRACE);
				}

				/**
				 * Runs an action on a worker thread and stops it after the policy's timeout,
				 * waited for to the nanosecond and converted before the worker starts. A worker
				 * that does not stop within the grace period halts the test process, since it
				 * would otherwise keep running untrusted code. The thread-creation
				 * check exempts exactly this method, by name.
				 *
				 * @param <T>          the action's result
				 * @param action       the action to bound
				 * @param defaultGrace the grace period when the policy names none
				 * @return the action's result
				 * @throws Throwable whatever the action threw, or a timeout naming the limit
				 */
				public static <T> T executeWithTimeout(TimedAction<T> action, Duration defaultGrace) throws Throwable {
					Duration timeout = timeout();
					long timeoutNanos = timeout.toNanos();
					long graceNanos = graceNanos(defaultGrace);
					ExecutorService executor = Executors.newSingleThreadExecutor(new WorkerFactory());
					Future<T> future = executor.submit(() -> call(action));
					try {
						return future.get(timeoutNanos, TimeUnit.NANOSECONDS);
					} catch (ExecutionException failure) {
						throw unwrapped(failure);
					} catch (TimeoutException expired) {
						terminate(future, executor, graceNanos);
						throw new TimeoutException(@MESSAGES@.localized("timeout.failure_message", format(timeout)));
					} finally {
						executor.shutdownNow();
					}
				}

				/**
				 * The policy's timeout.
				 *
				 * @return the timeout
				 */
				static Duration timeout() {
					return Duration.of(@SETTINGS@.@TIMEOUT@, TimeUnit.valueOf(@SETTINGS@.@UNIT@).toChronoUnit());
				}

				/**
				 * The policy's grace period in nanoseconds, or the caller's default.
				 *
				 * @param defaultGrace the caller's default
				 * @return the grace period in nanoseconds
				 */
				static long graceNanos(Duration defaultGrace) {
					if (@SETTINGS@.@GRACE@ < 0) {
						return defaultGrace.toNanos();
					}
					return Duration.of(@SETTINGS@.@GRACE@, TimeUnit.valueOf(@SETTINGS@.@GRACE_UNIT@).toChronoUnit())
							.toNanos();
				}

				/**
				 * Runs the action, passing on what a worker may throw.
				 *
				 * @param <T>    the action's result
				 * @param action the action
				 * @return the action's result
				 * @throws Exception whatever the action threw, wrapped if it is neither an
				 *                   exception nor an error
				 */
				private static <T> T call(TimedAction<T> action) throws Exception {
					try {
						return action.run();
					} catch (Exception | Error failure) {
						throw failure;
					} catch (Throwable other) {
						throw new ExecutionException(other);
					}
				}

				/**
				 * The failure the action threw, without the worker's wrapping.
				 *
				 * @param failure the worker's failure
				 * @return what the action threw
				 */
				private static Throwable unwrapped(ExecutionException failure) {
					Throwable cause = failure.getCause();
					if (cause instanceof ExecutionException wrapped && wrapped.getCause() != null) {
						return wrapped.getCause();
					}
					return cause;
				}

				/**
				 * Interrupts the worker and waits the grace period for it to stop, halting
				 * the test process if it does not.
				 *
				 * @param future     the worker's task
				 * @param executor   the worker's executor
				 * @param graceNanos the grace period in nanoseconds
				 */
				private static void terminate(Future<?> future, ExecutorService executor, long graceNanos) {
					executor.shutdown();
					future.cancel(true);
					if (!awaitTermination(executor, graceNanos)) {
						Runtime.getRuntime().halt(UNRESPONSIVE_EXIT_CODE);
						throw new AssertionError("Halting the test process returned without halting it");
					}
				}

				/**
				 * Waits for the executor to stop, at most the given time, keeping an
				 * interruption for the caller.
				 *
				 * @param executor     the executor
				 * @param timeoutNanos the longest wait in nanoseconds
				 * @return true when it stopped in time
				 */
				private static boolean awaitTermination(ExecutorService executor, long timeoutNanos) {
					long deadline = System.nanoTime() + timeoutNanos;
					boolean interrupted = false;
					try {
						while (!executor.isTerminated()) {
							long remainingNanos = deadline - System.nanoTime();
							if (remainingNanos <= 0) {
								return false;
							}
							try {
								if (executor.awaitTermination(remainingNanos, TimeUnit.NANOSECONDS)) {
									return true;
								}
							} catch (InterruptedException ignored) {
								interrupted = true;
							}
						}
						return true;
					} finally {
						if (interrupted) {
							Thread.currentThread().interrupt();
						}
					}
				}

				/**
				 * A duration in hours, minutes, seconds and milliseconds, as
				 * {@code @StrictTimeout} reports it.
				 *
				 * @param duration the duration
				 * @return the formatted duration
				 */
				private static String format(Duration duration) {
					List<String> parts = new ArrayList<>();
					long hours = duration.toHours();
					if (hours != 0) {
						parts.add(hours + " h");
					}
					if (duration.toMinutesPart() != 0) {
						parts.add(duration.toMinutesPart() + " min");
					}
					if (duration.toSecondsPart() != 0) {
						parts.add(duration.toSecondsPart() + " s");
					}
					if (duration.toMillisPart() != 0) {
						parts.add(duration.toMillisPart() + " ms");
					}
					return String.join(" ", parts);
				}

				/**
				 * An action that may throw anything, as a JUnit invocation may.
				 *
				 * @param <T> the action's result
				 */
				@FunctionalInterface
				public interface TimedAction<T> {

					/**
					 * Runs the action.
					 *
					 * @return its result
					 * @throws Throwable whatever it throws
					 */
					T run() throws Throwable;
				}

				/**
				 * Creates the timeout's worker threads. A class of its own, so the
				 * thread-creation check finds {@code executeWithTimeout} as the first frame
				 * of {@code GeneratedStrictTimeout} itself.
				 */
				static final class WorkerFactory implements ThreadFactory {

					/** Numbers the worker threads. */
					private static final AtomicInteger WORKER_ID = new AtomicInteger(1);

					/**
					 * Creates a daemon worker thread.
					 *
					 * @param runnable the work
					 * @return the thread
					 */
					@Override
					public Thread newThread(Runnable runnable) {
						Thread thread = new Thread(runnable, "ares-generated-timeout-" + WORKER_ID.getAndIncrement());
						thread.setDaemon(true);
						thread.setPriority(Thread.NORM_PRIORITY);
						return thread;
					}
				}
			}
			""";

	/**
	 * Source text of the JUnit sentinel test, before the placeholders are filled.
	 */
	private static final String JUPITER_SENTINEL_SOURCE = """
			package de.tum.cit.ase.ares.generated;

			import org.junit.jupiter.api.Test;

			/**
			 * Generated by Ares. Fails when the generated strict timeout did not time this
			 * test, so a missing hook shows up as a red test instead of unbounded tests.
			 */
			class GeneratedStrictTimeoutSentinelTest {

				/** Checks that the generated strict timeout timed this test. */
				@Test
				void strictTimeoutIsActive() {
					if (!GeneratedStrictTimeout.isGuarding(GeneratedStrictTimeoutSentinelTest.class.getName() + "#strictTimeoutIsActive")) {
						throw new AssertionError(@MESSAGES@.localized("generated.strict.timeout.inactive"));
					}
				}

			}
			""";

	/** Prevents instantiation: this class only holds source texts. */
	private StrictTimeoutSources() {
		throw new IllegalStateException("StrictTimeoutSources is a utility class and should not be instantiated");
	}

	/**
	 * The JUnit Jupiter interceptor's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterHook(@Nonnull String messagesClass) {
		return fill(JUPITER_HOOK_SOURCE, messagesClass);
	}

	/**
	 * The JUnit sentinel test's source.
	 *
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text
	 */
	@Nonnull
	static String jupiterSentinel(@Nonnull String messagesClass) {
		return fill(JUPITER_SENTINEL_SOURCE, messagesClass);
	}

	/**
	 * Fills the placeholders of a source text.
	 *
	 * @param source        the source text with placeholders.
	 * @param messagesClass fully qualified name of the copied {@code Messages}.
	 * @return the source text with every placeholder replaced
	 */
	@Nonnull
	private static String fill(@Nonnull String source, @Nonnull String messagesClass) {
		return source.replace(MESSAGES, messagesClass).replace(SETTINGS, TestBehaviorConfiguration.GENERATED_CLASS_NAME)
				.replace(GRACE_UNIT, TestBehaviorConfiguration.STRICT_TIMEOUTS_GRACE_UNIT_FIELD_NAME)
				.replace(GRACE, TestBehaviorConfiguration.STRICT_TIMEOUTS_GRACE_FIELD_NAME)
				.replace(TIMEOUT, TestBehaviorConfiguration.STRICT_TIMEOUTS_TIMEOUT_FIELD_NAME)
				.replace(UNIT, TestBehaviorConfiguration.STRICT_TIMEOUTS_TIME_UNIT_FIELD_NAME)
				.replace("\n", System.lineSeparator());
	}
}
