# This is an example configuration file for the programming exercise "ExampleProgrammingExercise".
theProgrammingLanguageOfTheSupervisedCodeIs: JAVA_USING_GRADLE_AND_INSTRUMENTATION,
theFollowingFeaturesAreAllowedForTheSupervisedCode: [
  regardingFileSystemInteractions: [
    itIsAllowedTo: [
      readAllFiles: true,
      overwriteAllFiles: true,
      executeAllFiles: true,
      onThisPathAndAllPathsBelow: "/Path"
    ]
  ],
  regardingNetworkConnections: [
    itIsAllowedTo: [
      openConnections: true,
      sendData: true,
      receiveData: true,
      ontheHost: "www.example.com",
      onThePort: 80
    ]
  ],
  regardingCommandExecutionsForTheStudents: [
    itIsAllowedTo: [
      executeTheCommand: "ls",
      withTheseArguments: [ "-l" ]
    ]
  ],
  regardingThreadCreationsForTheStudents: [
    itIsAllowedTo: [
      createTheFollowingNumberOfThreads: 10,
      ofThisClass: "java.lang.Thread"
    ]
  ],
  regardingPackageImport: [
    itIsAllowedTo: [
      importTheFollowingPackage: "java.util"
    ]
  ],
]
