regardingTheSupervisedCode:
  theFollowingProgrammingLanguageConfigurationIsUsed: JAVA_USING_MAVEN_ARCHUNIT_AND_INSTRUMENTATION
  theSupervisedCodeUsesTheFollowingPackage: "de.tum.cit.ase"
  theMainClassInsideThisPackageIs: "Main"
  theFollowingClassesAreTestClasses:
    - "de.tum.cit.ase.example.ExampleTest"
  theFollowingResourceAccessesArePermitted:
    regardingFileSystemInteractions:
      - onThisPathAndAllPathsBelow: "pom.xml"
        readAllFiles: true
        overwriteAllFiles: true
        executeAllFiles: true
        deleteAllFiles: false
    regardingNetworkConnections:
      - onTheHost: "www.example.com"
        onThePort: 80
        openConnections: true
        sendData: true
        receiveData: true
    regardingCommandExecutions:
      - executeTheCommand: "ls"
        withTheseArguments:
          - "-l"
    regardingThreadCreations:
      - createTheFollowingNumberOfThreads: 10
        ofThisClass: "instrumentation.lang.Thread"
    regardingPackageImports:
      - importTheFollowingPackage: "instrumentation.util"