programmingLanguage: JAVA
allowedFileSystemInteractions:
  - path: "/Path1"
    read: true
    write: false
    execute: false
  - path: "/Path2"
    read: false
    write: true
    execute: false
  - path: "/Path3"
    read: false
    write: false
    execute: true
  - path: "/Path4"
    read: true
    write: true
    execute: true