regardingTheSupervisedCode:
  theFollowingProgrammingLanguageConfigurationIsUsed: JAVA_USING_MAVEN_ARCHUNIT_AND_INSTRUMENTATION
  theProgrammingLanguageUsesTheFollowingPackage: "de.tum.cit.ase"
  theFollowingClassesAreTestClasses:
    - "de.tum.cit.ase.example.ExampleTest"
  theFollowingResourceAccessesArePermitted:
    regardingFileSystemInteractions:
      - readAllFiles: true
        overwriteAllFiles: true
        executeAllFiles: true
        deleteAllFiles: false
        onThisPathAndAllPathsBelow: "pom.xml"
    regardingNetworkConnections:
      - openConnections: true
        sendData: true
        receiveData: true
        onTheHost: "www.example.com"
        onThePort: 80
    regardingCommandExecutions:
      - executeTheCommand: "ls"
        withTheseArguments:
          - "-l"
    regardingThreadCreations:
      - createTheFollowingNumberOfThreads: 10
        ofThisClass: "instrumentation.lang.Thread"
    regardingPackageImports:
      - importTheFollowingPackage: "instrumentation.util"