package de.tum.cit.ase.ares.documentation;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * The rules that hold for every {@code _category_.json} in both guides.
 * <p>
 * Both sidebars are autogenerated, so the sidebar a reader sees is produced
 * entirely by these files together with the {@code sidebar_position} front
 * matter of the pages. Nothing in the Docusaurus build validates them: a
 * category with no label, a category whose position collides with a sibling
 * page, or a category that declares a generated index while also holding a real
 * {@code index.md} all build successfully and simply render wrongly.
 * <p>
 * The expected-path sets in {@link SiteWideDocumentationStructureTest} cannot
 * see any of this, because a category file is not a page.
 *
 * @since 2.1.2
 * @author Markus Paulsen
 */
class CategoryMetadataStructureTest {

	/**
	 * Parsed rather than matched with regular expressions.
	 * <p>
	 * A pattern for {@code "type"} finds the first such key anywhere in the file,
	 * which is not necessarily the one inside {@code link}, and a pattern for
	 * {@code "label"} cannot survive a label containing an escaped quotation mark.
	 * Both would report a verdict about a field the file does not actually declare.
	 */
	private static final ObjectMapper MAPPER = new ObjectMapper();

	/** Every category file of both guides. */
	private static List<Path> categoryFiles() {
		try (Stream<Path> entries = Files.walk(DocumentationPages.DOCS)) {
			return entries.filter(Files::isRegularFile)
					.filter(path -> "_category_.json".equals(path.getFileName().toString())).sorted().toList();
		} catch (IOException exception) {
			throw new UncheckedIOException("Could not walk " + DocumentationPages.DOCS, exception);
		}
	}

	private static JsonNode read(Path file) {
		try {
			return MAPPER.readTree(Files.readString(file, StandardCharsets.UTF_8));
		} catch (IOException exception) {
			throw new UncheckedIOException(file + " is not valid JSON", exception);
		}
	}

	@ParameterizedTest(name = "{0} declares a label and a usable position")
	@MethodSource("categoryFiles")
	void everyCategoryDeclaresALabelAndAPosition(Path file) {
		JsonNode category = read(file);

		assertTrue(category.hasNonNull("label"), file + " must declare a \"label\".");
		assertFalse(category.get("label").asText().isBlank(), file + " must declare a non-empty \"label\".");

		assertTrue(category.hasNonNull("position"), file + " must declare a \"position\".");
		assertTrue(category.get("position").asInt() > 0, file + " must declare a positive \"position\".");
	}

	/**
	 * A category either has a real index document or a generated one, never both.
	 * <p>
	 * With an {@code index.md} present, Docusaurus already treats that document as
	 * the category landing page. Declaring {@code generated-index} as well produces
	 * two competing notions of where the category points, and the index page then
	 * sits in the sidebar as an ordinary child of itself.
	 */
	@ParameterizedTest(name = "{0} has one landing page, not two")
	@MethodSource("categoryFiles")
	void noCategoryDeclaresAGeneratedIndexBesideARealOne(Path file) {
		boolean hasIndexDocument = Files.isRegularFile(file.resolveSibling("index.md"));

		JsonNode linkType = read(file).path("link").path("type");
		boolean declaresGeneratedIndex = "generated-index".equals(linkType.asText(""));

		if (hasIndexDocument) {
			assertFalse(declaresGeneratedIndex,
					file + " sits beside an index.md, which is already the category landing page. "
							+ "Remove the generated-index link.");
		} else {
			assertTrue(declaresGeneratedIndex, file + " has no index.md, so it must declare a generated-index link. "
					+ "Without either, the category is not clickable.");
		}
	}

	/**
	 * Within one directory, no two sidebar entries may claim the same position.
	 * <p>
	 * Compared across both kinds of entry, because a subcategory and a page are
	 * siblings in the rendered sidebar even though they are different kinds of file
	 * on disk. Comparing categories only against categories misses the collision
	 * that actually happens during a restructure, where a page keeps a position a
	 * new subcategory has just taken.
	 */
	@Test
	void noTwoSiblingsClaimTheSameSidebarPosition() {
		Map<Path, Map<Integer, List<String>>> byDirectory = new HashMap<>();

		for (Path category : categoryFiles()) {
			JsonNode position = read(category).path("position");
			if (position.isInt()) {
				record(byDirectory, category.getParent().getParent(), position.asInt(),
						category.getParent().getFileName() + "/");
			}
		}
		for (Path page : DocumentationPages.pagesBelow()) {
			int position = DocumentationPages.sidebarPosition(DocumentationPages.read(page));
			if (position > 0) {
				record(byDirectory, page.getParent(), position, page.getFileName().toString());
			}
		}

		List<String> collisions = new ArrayList<>();
		byDirectory.forEach((directory, positions) -> positions.forEach((position, entries) -> {
			if (entries.size() > 1) {
				collisions.add(directory + " position " + position + ": " + entries.stream().sorted().toList());
			}
		}));

		assertEquals(List.of(), collisions.stream().sorted().toList(),
				"Two sidebar entries in the same directory claim one position. Docusaurus then orders them "
						+ "alphabetically, which is rarely what was meant.");
	}

	private static void record(Map<Path, Map<Integer, List<String>>> byDirectory, Path directory, int position,
			String entry) {
		byDirectory.computeIfAbsent(directory, key -> new HashMap<>())
				.computeIfAbsent(position, key -> new ArrayList<>()).add(entry);
	}
}
