import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
// Ordering comes from `sidebar_position` front matter and `_category_.json` files, so a new
// page appears in the sidebar without an edit here.
const sidebars: SidebarsConfig = {
    sidebar: [
        {
            type: 'autogenerated',
            dirName: '.',
        },
    ],
};

export default sidebars;
