# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          sudo rm -rf /usr/bin/mvn
          sudo wget -q -O - "https://apache.osuosl.org/maven/maven-3/3.9.8/binaries/apache-maven-3.9.8-bin.tar.gz" | sudo tar xzf - -C /usr/share
          sudo ln -s /usr/share/apache-maven-3.9.8/bin/mvn /usr/bin/mvn

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        run: |
          mvn clean
          mvn package -DskipTests
          mvn test

      - name: Run Tests on Student Submission
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/sarpsahinalp/test-student-submission.git
          mkdir test-student-submission/libs
          cp target/*.jar test-student-submission/libs
          cd test-student-submission
          ./gradlew build
          ./gradlew test
